"""phase7 email writer

Revision ID: 20260525_0007
Revises: 20260525_0006
Create Date: 2026-05-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260525_0007"
down_revision: str | None = "20260525_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table("email_generation_runs", sa.Column("id", sa.Integer(), nullable=False), sa.Column("run_id", sa.String(length=80), nullable=False), sa.Column("campaign_id", sa.Integer(), nullable=False), sa.Column("operation", sa.String(length=60), nullable=False), sa.Column("status", sa.String(length=80), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False), sa.Column("model_provider", sa.String(length=80), nullable=True), sa.Column("model_name", sa.String(length=120), nullable=True), sa.Column("model_config_json", sa.JSON(), nullable=True), sa.Column("prompt_template_version", sa.String(length=40), nullable=True), sa.Column("input_candidate_count", sa.Integer(), nullable=False), sa.Column("draft_created_count", sa.Integer(), nullable=False), sa.Column("manual_review_count", sa.Integer(), nullable=False), sa.Column("blocked_count", sa.Integer(), nullable=False), sa.Column("failed_count", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("finished_at", sa.DateTime(), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("run_id"))
    op.create_table("email_prompt_templates", sa.Column("id", sa.Integer(), nullable=False), sa.Column("template_slug", sa.String(length=160), nullable=False), sa.Column("template_name", sa.String(length=255), nullable=False), sa.Column("campaign_lane", sa.String(length=80), nullable=False), sa.Column("category", sa.String(length=120), nullable=True), sa.Column("version", sa.String(length=40), nullable=False), sa.Column("status", sa.String(length=40), nullable=False), sa.Column("system_prompt", sa.Text(), nullable=False), sa.Column("user_prompt_template", sa.Text(), nullable=False), sa.Column("output_schema_json", sa.JSON(), nullable=False), sa.Column("max_words", sa.Integer(), nullable=False), sa.Column("tone_profile", sa.String(length=120), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("template_slug"))
    op.create_table("prompt_template_snapshots", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_generation_run_id", sa.Integer(), nullable=False), sa.Column("template_id", sa.Integer(), nullable=False), sa.Column("template_slug", sa.String(length=160), nullable=False), sa.Column("version", sa.String(length=40), nullable=False), sa.Column("system_prompt_hash", sa.String(length=128), nullable=False), sa.Column("user_prompt_hash", sa.String(length=128), nullable=False), sa.Column("output_schema_json", sa.JSON(), nullable=False), sa.Column("model_config_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_generation_run_id"], ["email_generation_runs.id"]), sa.ForeignKeyConstraint(["template_id"], ["email_prompt_templates.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_generation_inputs", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_generation_run_id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("phase6_decision_id", sa.Integer(), nullable=True), sa.Column("input_snapshot_json", sa.JSON(), nullable=False), sa.Column("input_snapshot_hash", sa.String(length=128), nullable=False), sa.Column("allowed_claims_json", sa.JSON(), nullable=False), sa.Column("blocked_claims_json", sa.JSON(), nullable=False), sa.Column("offer_blocks_json", sa.JSON(), nullable=False), sa.Column("verified_evidence_json", sa.JSON(), nullable=False), sa.Column("style_constraints_json", sa.JSON(), nullable=False), sa.Column("cta_options_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_generation_run_id"], ["email_generation_runs.id"]), sa.ForeignKeyConstraint(["phase6_decision_id"], ["phase6_candidate_decisions.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_subject_candidates", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_generation_run_id", sa.Integer(), nullable=False), sa.Column("subject_text", sa.String(length=255), nullable=False), sa.Column("variant_label", sa.String(length=20), nullable=False), sa.Column("word_count", sa.Integer(), nullable=False), sa.Column("risk_flags_json", sa.JSON(), nullable=False), sa.Column("allowed_for_judge", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_generation_run_id"], ["email_generation_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_draft_variants", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_draft_id", sa.Integer(), nullable=True), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_generation_run_id", sa.Integer(), nullable=False), sa.Column("variant_label", sa.String(length=20), nullable=False), sa.Column("subject_text", sa.String(length=255), nullable=False), sa.Column("body_text", sa.Text(), nullable=False), sa.Column("word_count", sa.Integer(), nullable=False), sa.Column("tone_profile", sa.String(length=120), nullable=False), sa.Column("campaign_lane", sa.String(length=80), nullable=False), sa.Column("category", sa.String(length=120), nullable=False), sa.Column("status", sa.String(length=80), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_draft_id"], ["email_drafts.id"]), sa.ForeignKeyConstraint(["email_generation_run_id"], ["email_generation_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_draft_evidence_links", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("evidence_type", sa.String(length=120), nullable=False), sa.Column("evidence_source_table", sa.String(length=120), nullable=False), sa.Column("evidence_source_id", sa.Integer(), nullable=True), sa.Column("used_in_sentence", sa.String(length=1000), nullable=True), sa.Column("confidence", sa.Float(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_draft_claim_usage", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("claim_type", sa.String(length=120), nullable=False), sa.Column("claim_text", sa.String(length=1000), nullable=False), sa.Column("claim_permission_id", sa.Integer(), nullable=True), sa.Column("allowed", sa.Boolean(), nullable=False), sa.Column("risk_level", sa.String(length=40), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_draft_precheck_results", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("precheck_status", sa.String(length=40), nullable=False), sa.Column("word_count_ok", sa.Boolean(), nullable=False), sa.Column("subject_ok", sa.Boolean(), nullable=False), sa.Column("personalization_ok", sa.Boolean(), nullable=False), sa.Column("blocked_words_ok", sa.Boolean(), nullable=False), sa.Column("claim_permission_ok", sa.Boolean(), nullable=False), sa.Column("economic_claim_ok", sa.Boolean(), nullable=False), sa.Column("tone_ok", sa.Boolean(), nullable=False), sa.Column("cta_ok", sa.Boolean(), nullable=False), sa.Column("unsubscribe_placeholder_ok", sa.Boolean(), nullable=False), sa.Column("similarity_ok", sa.Boolean(), nullable=False), sa.Column("prompt_injection_ok", sa.Boolean(), nullable=False), sa.Column("risk_flags_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_draft_similarity_results", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("compared_against_draft_id", sa.Integer(), nullable=True), sa.Column("similarity_score", sa.Float(), nullable=False), sa.Column("repeated_phrases_json", sa.JSON(), nullable=True), sa.Column("decision", sa.String(length=40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["compared_against_draft_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("phase7_candidate_decisions", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_generation_run_id", sa.Integer(), nullable=False), sa.Column("decision", sa.String(length=80), nullable=False), sa.Column("ready_for_phase8", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("hold_reason", sa.String(length=500), nullable=True), sa.Column("reject_reason", sa.String(length=500), nullable=True), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_generation_run_id"], ["email_generation_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_generation_manual_review_items", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_generation_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=True), sa.Column("review_type", sa.String(length=80), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("recommended_action", sa.String(length=500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("status", sa.String(length=40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_generation_run_id"], ["email_generation_runs.id"]), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for table in [
        "email_generation_manual_review_items",
        "phase7_candidate_decisions",
        "email_draft_similarity_results",
        "email_draft_precheck_results",
        "email_draft_claim_usage",
        "email_draft_evidence_links",
        "email_draft_variants",
        "email_subject_candidates",
        "email_generation_inputs",
        "prompt_template_snapshots",
        "email_prompt_templates",
        "email_generation_runs",
    ]:
        op.drop_table(table)
