"""phase8 email judge

Revision ID: 20260525_0008
Revises: 20260525_0007
Create Date: 2026-05-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260525_0008"
down_revision: str | None = "20260525_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table("email_judge_runs", sa.Column("id", sa.Integer(), nullable=False), sa.Column("run_id", sa.String(length=80), nullable=False), sa.Column("campaign_id", sa.Integer(), nullable=False), sa.Column("operation", sa.String(length=60), nullable=False), sa.Column("status", sa.String(length=80), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False), sa.Column("judge_mode", sa.String(length=40), nullable=False), sa.Column("model_provider", sa.String(length=80), nullable=True), sa.Column("model_name", sa.String(length=120), nullable=True), sa.Column("model_config_json", sa.JSON(), nullable=True), sa.Column("input_draft_count", sa.Integer(), nullable=False), sa.Column("approved_count", sa.Integer(), nullable=False), sa.Column("approved_with_warnings_count", sa.Integer(), nullable=False), sa.Column("rewrite_required_count", sa.Integer(), nullable=False), sa.Column("manual_review_count", sa.Integer(), nullable=False), sa.Column("blocked_count", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("finished_at", sa.DateTime(), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("run_id"))
    op.create_table("email_rule_judge_results", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("passed", sa.Boolean(), nullable=False), sa.Column("blocker_count", sa.Integer(), nullable=False), sa.Column("warning_count", sa.Integer(), nullable=False), sa.Column("truthfulness_passed", sa.Boolean(), nullable=False), sa.Column("evidence_alignment_passed", sa.Boolean(), nullable=False), sa.Column("blocked_claims_passed", sa.Boolean(), nullable=False), sa.Column("unsubscribe_passed", sa.Boolean(), nullable=False), sa.Column("sender_identity_passed", sa.Boolean(), nullable=False), sa.Column("cta_passed", sa.Boolean(), nullable=False), sa.Column("creepy_evidence_passed", sa.Boolean(), nullable=False), sa.Column("economic_claims_passed", sa.Boolean(), nullable=False), sa.Column("findings_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_ai_judge_results", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("judge_model", sa.String(length=120), nullable=True), sa.Column("judge_prompt_version", sa.String(length=40), nullable=True), sa.Column("overall_quality_score", sa.Float(), nullable=False), sa.Column("truthfulness_score", sa.Float(), nullable=False), sa.Column("evidence_alignment_score", sa.Float(), nullable=False), sa.Column("personalization_score", sa.Float(), nullable=False), sa.Column("human_likeness_score", sa.Float(), nullable=False), sa.Column("non_promotional_score", sa.Float(), nullable=False), sa.Column("economic_claim_safety_score", sa.Float(), nullable=False), sa.Column("compliance_readiness_score", sa.Float(), nullable=False), sa.Column("spam_risk_score", sa.Float(), nullable=False), sa.Column("cta_quality_score", sa.Float(), nullable=False), sa.Column("decision", sa.String(length=40), nullable=False), sa.Column("findings_json", sa.JSON(), nullable=False), sa.Column("rewrite_brief_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_judge_findings", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("finding_type", sa.String(length=80), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("message", sa.String(length=1000), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_judge_decisions", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("decision", sa.String(length=80), nullable=False), sa.Column("quality_score", sa.Float(), nullable=False), sa.Column("ready_for_phase9", sa.Boolean(), nullable=False), sa.Column("preferred_variant", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("rewrite_required", sa.Boolean(), nullable=False), sa.Column("blocked_reason", sa.String(length=500), nullable=True), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_rewrite_briefs", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("rewrite_reason", sa.String(length=500), nullable=False), sa.Column("rewrite_instructions_json", sa.JSON(), nullable=False), sa.Column("must_keep_json", sa.JSON(), nullable=False), sa.Column("must_remove_json", sa.JSON(), nullable=False), sa.Column("must_soften_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_variant_selections", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("preferred_email_draft_variant_id", sa.Integer(), nullable=True), sa.Column("backup_email_draft_variant_id", sa.Integer(), nullable=True), sa.Column("selection_reason", sa.String(length=500), nullable=False), sa.Column("rejected_variant_ids_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["backup_email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.ForeignKeyConstraint(["preferred_email_draft_variant_id"], ["email_draft_variants.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_judge_disagreements", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=False), sa.Column("rule_decision", sa.String(length=80), nullable=False), sa.Column("ai_decision", sa.String(length=80), nullable=True), sa.Column("final_resolution", sa.String(length=80), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("phase8_candidate_decisions", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("decision", sa.String(length=80), nullable=False), sa.Column("preferred_email_draft_variant_id", sa.Integer(), nullable=True), sa.Column("ready_for_phase9", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("rewrite_required", sa.Boolean(), nullable=False), sa.Column("blocked", sa.Boolean(), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.ForeignKeyConstraint(["preferred_email_draft_variant_id"], ["email_draft_variants.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("phase8_manual_review_items", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), nullable=True), sa.Column("review_type", sa.String(length=80), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("recommended_action", sa.String(length=500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("status", sa.String(length=40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["email_draft_variant_id"], ["email_draft_variants.id"]), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("email_judge_prompt_templates", sa.Column("id", sa.Integer(), nullable=False), sa.Column("template_slug", sa.String(length=160), nullable=False), sa.Column("template_name", sa.String(length=255), nullable=False), sa.Column("version", sa.String(length=40), nullable=False), sa.Column("status", sa.String(length=40), nullable=False), sa.Column("system_prompt", sa.Text(), nullable=False), sa.Column("user_prompt_template", sa.Text(), nullable=False), sa.Column("output_schema_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("template_slug"))
    op.create_table("email_judge_prompt_snapshots", sa.Column("id", sa.Integer(), nullable=False), sa.Column("email_judge_run_id", sa.Integer(), nullable=False), sa.Column("template_id", sa.Integer(), nullable=False), sa.Column("template_slug", sa.String(length=160), nullable=False), sa.Column("version", sa.String(length=40), nullable=False), sa.Column("system_prompt_hash", sa.String(length=128), nullable=False), sa.Column("user_prompt_hash", sa.String(length=128), nullable=False), sa.Column("output_schema_json", sa.JSON(), nullable=False), sa.Column("model_config_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["email_judge_run_id"], ["email_judge_runs.id"]), sa.ForeignKeyConstraint(["template_id"], ["email_judge_prompt_templates.id"]), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for table in ["email_judge_prompt_snapshots", "email_judge_prompt_templates", "phase8_manual_review_items", "phase8_candidate_decisions", "email_judge_disagreements", "email_variant_selections", "email_rewrite_briefs", "email_judge_decisions", "email_judge_findings", "email_ai_judge_results", "email_rule_judge_results", "email_judge_runs"]:
        op.drop_table(table)
