"""phase6 insight offer

Revision ID: 20260525_0006
Revises: 20260525_0005
Create Date: 2026-05-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260525_0006"
down_revision: str | None = "20260525_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table("insight_runs", sa.Column("id", sa.Integer(), nullable=False), sa.Column("run_id", sa.String(length=80), nullable=False), sa.Column("campaign_id", sa.Integer(), nullable=False), sa.Column("operation", sa.String(length=40), nullable=False), sa.Column("status", sa.String(length=60), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False), sa.Column("input_candidate_count", sa.Integer(), nullable=False), sa.Column("insight_created_count", sa.Integer(), nullable=False), sa.Column("offer_matched_count", sa.Integer(), nullable=False), sa.Column("manual_review_count", sa.Integer(), nullable=False), sa.Column("hold_count", sa.Integer(), nullable=False), sa.Column("rejected_count", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("finished_at", sa.DateTime(), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("run_id"))
    op.create_table("offer_playbooks", sa.Column("id", sa.Integer(), nullable=False), sa.Column("category", sa.String(length=120), nullable=False), sa.Column("playbook_slug", sa.String(length=160), nullable=False), sa.Column("playbook_name", sa.String(length=255), nullable=False), sa.Column("status", sa.String(length=40), nullable=False), sa.Column("version", sa.String(length=40), nullable=False), sa.Column("description", sa.String(length=1000), nullable=False), sa.Column("default_offer_package", sa.String(length=80), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("playbook_slug"))
    op.create_table("offer_modules", sa.Column("id", sa.Integer(), nullable=False), sa.Column("playbook_id", sa.Integer(), nullable=False), sa.Column("module_slug", sa.String(length=160), nullable=False), sa.Column("module_name", sa.String(length=255), nullable=False), sa.Column("module_type", sa.String(length=40), nullable=False), sa.Column("description", sa.String(length=1000), nullable=False), sa.Column("complexity_level", sa.String(length=40), nullable=False), sa.Column("implementation_complexity", sa.String(length=40), nullable=False), sa.Column("maintenance_risk", sa.String(length=40), nullable=False), sa.Column("wordpress_fit", sa.String(length=40), nullable=False), sa.Column("custom_code_required", sa.Boolean(), nullable=False), sa.Column("third_party_dependency", sa.String(length=255), nullable=True), sa.Column("estimated_build_effort", sa.String(length=120), nullable=False), sa.Column("economic_angle", sa.String(length=500), nullable=True), sa.Column("is_core", sa.Boolean(), nullable=False), sa.Column("is_optional", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["playbook_id"], ["offer_playbooks.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("candidate_business_insights", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("category", sa.String(length=120), nullable=False), sa.Column("campaign_lane", sa.String(length=80), nullable=False), sa.Column("business_context_summary", sa.String(length=1000), nullable=False), sa.Column("likely_customer_path", sa.String(length=1000), nullable=False), sa.Column("main_friction_points_json", sa.JSON(), nullable=False), sa.Column("opportunity_summary", sa.String(length=1000), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("candidate_pain_point_hypotheses", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("pain_point_type", sa.String(length=80), nullable=False), sa.Column("pain_point_text", sa.String(length=1000), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("requires_verification", sa.Boolean(), nullable=False), sa.Column("allowed_for_future_copy", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("candidate_offer_matches", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("playbook_id", sa.Integer(), nullable=False), sa.Column("offer_package", sa.String(length=80), nullable=False), sa.Column("offer_fit_score", sa.Float(), nullable=False), sa.Column("offer_confidence", sa.Float(), nullable=False), sa.Column("offer_summary", sa.String(length=1000), nullable=False), sa.Column("internal_offer_analysis", sa.String(length=1500), nullable=False), sa.Column("email_safe_offer_summary", sa.String(length=1000), nullable=False), sa.Column("primary_value_angle", sa.String(length=500), nullable=False), sa.Column("secondary_value_angles_json", sa.JSON(), nullable=False), sa.Column("selected_module_ids_json", sa.JSON(), nullable=False), sa.Column("excluded_module_ids_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.ForeignKeyConstraint(["playbook_id"], ["offer_playbooks.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("candidate_economic_value_angles", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("angle_type", sa.String(length=80), nullable=False), sa.Column("angle_text", sa.String(length=1000), nullable=False), sa.Column("claim_strength", sa.String(length=40), nullable=False), sa.Column("allowed_for_future_copy", sa.Boolean(), nullable=False), sa.Column("requires_verification", sa.Boolean(), nullable=False), sa.Column("blocked_reason", sa.String(length=500), nullable=True), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("future_email_offer_blocks", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("block_type", sa.String(length=80), nullable=False), sa.Column("block_text", sa.String(length=1000), nullable=False), sa.Column("allowed_for_phase7", sa.Boolean(), nullable=False), sa.Column("requires_judge", sa.Boolean(), nullable=False), sa.Column("risk_flags_json", sa.JSON(), nullable=False), sa.Column("supporting_evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("offer_readiness_gates", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("gate_name", sa.String(length=80), nullable=False), sa.Column("passed", sa.Boolean(), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("price_positioning_recommendations", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("price_positioning", sa.String(length=80), nullable=False), sa.Column("price_visibility", sa.String(length=40), nullable=False), sa.Column("price_risk", sa.String(length=255), nullable=False), sa.Column("recommended_language_json", sa.JSON(), nullable=False), sa.Column("blocked_language_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("implementation_feasibility_notes", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("module_slug", sa.String(length=160), nullable=False), sa.Column("feasibility_level", sa.String(length=60), nullable=False), sa.Column("implementation_note", sa.String(length=500), nullable=False), sa.Column("risk_level", sa.String(length=40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("blocked_offer_claims", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("claim_text", sa.String(length=1000), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("phase6_candidate_decisions", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("decision", sa.String(length=80), nullable=False), sa.Column("ready_for_phase7", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("hold_reason", sa.String(length=500), nullable=True), sa.Column("reject_reason", sa.String(length=500), nullable=True), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("offer_manual_review_items", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("insight_run_id", sa.Integer(), nullable=False), sa.Column("review_type", sa.String(length=80), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("recommended_action", sa.String(length=500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("status", sa.String(length=40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["insight_run_id"], ["insight_runs.id"]), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for table in [
        "offer_manual_review_items",
        "phase6_candidate_decisions",
        "blocked_offer_claims",
        "implementation_feasibility_notes",
        "price_positioning_recommendations",
        "offer_readiness_gates",
        "future_email_offer_blocks",
        "candidate_economic_value_angles",
        "candidate_offer_matches",
        "candidate_pain_point_hypotheses",
        "candidate_business_insights",
        "offer_modules",
        "offer_playbooks",
        "insight_runs",
    ]:
        op.drop_table(table)
