"""phase 4 verification

Revision ID: 20260525_0004
Revises: 20260525_0003
Create Date: 2026-05-25
"""

from alembic import op
import sqlalchemy as sa

revision = "20260525_0004"
down_revision = "20260525_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("verification_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("run_id", sa.String(80), unique=True, nullable=False), sa.Column("campaign_id", sa.Integer(), sa.ForeignKey("campaigns.id"), nullable=True), sa.Column("operation", sa.String(80), nullable=False), sa.Column("status", sa.String(60), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False), sa.Column("input_candidate_count", sa.Integer(), nullable=False), sa.Column("verified_count", sa.Integer(), nullable=False), sa.Column("manual_review_count", sa.Integer(), nullable=False), sa.Column("rejected_count", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("finished_at", sa.DateTime(), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("search_queries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("source_name", sa.String(40), nullable=False), sa.Column("query_text_redacted", sa.String(1000), nullable=False), sa.Column("query_type", sa.String(80), nullable=False), sa.Column("cache_key", sa.String(255), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False), sa.Column("executed_at", sa.DateTime(), nullable=True), sa.Column("result_count", sa.Integer(), nullable=True), sa.Column("duration_ms", sa.Integer(), nullable=True), sa.Column("status", sa.String(60), nullable=False), sa.Column("error_message", sa.String(500), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("search_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("search_query_id", sa.Integer(), sa.ForeignKey("search_queries.id"), nullable=False), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("title", sa.String(500), nullable=True), sa.Column("url", sa.String(1000), nullable=False), sa.Column("domain", sa.String(255), nullable=False), sa.Column("snippet", sa.String(2000), nullable=True), sa.Column("rank", sa.Integer(), nullable=False), sa.Column("result_type", sa.String(80), nullable=False), sa.Column("domain_classification", sa.String(80), nullable=True), sa.Column("raw_payload_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("url_probe_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("url", sa.String(1000), nullable=False), sa.Column("domain", sa.String(255), nullable=False), sa.Column("final_url", sa.String(1000), nullable=True), sa.Column("status_code", sa.Integer(), nullable=True), sa.Column("is_redirect", sa.Boolean(), nullable=False), sa.Column("redirect_chain_json", sa.JSON(), nullable=True), sa.Column("title", sa.String(500), nullable=True), sa.Column("meta_description", sa.String(1000), nullable=True), sa.Column("content_sample_hash", sa.String(128), nullable=True), sa.Column("probe_status", sa.String(60), nullable=False), sa.Column("duration_ms", sa.Integer(), nullable=True), sa.Column("error_type", sa.String(120), nullable=True), sa.Column("error_message", sa.String(500), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("candidate_web_presence_verifications", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("website_status", sa.String(80), nullable=False), sa.Column("official_website_url", sa.String(1000), nullable=True), sa.Column("official_website_domain", sa.String(255), nullable=True), sa.Column("website_confidence", sa.Float(), nullable=False), sa.Column("website_ownership_confidence", sa.Float(), nullable=False), sa.Column("website_strength_score", sa.Float(), nullable=True), sa.Column("social_only", sa.Boolean(), nullable=False), sa.Column("directory_only", sa.Boolean(), nullable=False), sa.Column("weak_website", sa.Boolean(), nullable=False), sa.Column("no_website_claim_allowed", sa.Boolean(), nullable=False), sa.Column("no_website_claim_text", sa.String(500), nullable=True), sa.Column("requires_manual_review", sa.Boolean(), nullable=False), sa.Column("decision_reason", sa.String(500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("verified_at", sa.DateTime(), nullable=False), sa.Column("stale_after", sa.DateTime(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("contact_candidates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("contact_type", sa.String(40), nullable=False), sa.Column("contact_value", sa.String(1000), nullable=False), sa.Column("contact_domain", sa.String(255), nullable=True), sa.Column("contact_source_url", sa.String(1000), nullable=True), sa.Column("contact_source_type", sa.String(60), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("risk_level", sa.String(40), nullable=False), sa.Column("allowed_for_outreach", sa.Boolean(), nullable=False), sa.Column("requires_manual_review", sa.Boolean(), nullable=False), sa.Column("blocked_reason", sa.String(500), nullable=True), sa.Column("evidence_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("candidate_contact_verifications", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("best_email", sa.String(255), nullable=True), sa.Column("best_email_type", sa.String(60), nullable=True), sa.Column("best_email_confidence", sa.Float(), nullable=True), sa.Column("best_contact_url", sa.String(1000), nullable=True), sa.Column("contact_status", sa.String(80), nullable=False), sa.Column("outreach_contact_allowed", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("decision_reason", sa.String(500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("phase4_candidate_decisions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("decision", sa.String(80), nullable=False), sa.Column("decision_confidence", sa.Float(), nullable=False), sa.Column("website_status", sa.String(80), nullable=False), sa.Column("contact_status", sa.String(80), nullable=False), sa.Column("ready_for_phase5", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("reject_reason", sa.String(500), nullable=True), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("verified_personalization_evidence", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("evidence_type", sa.String(120), nullable=False), sa.Column("evidence_value", sa.String(1000), nullable=False), sa.Column("evidence_source", sa.String(120), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("allowed_for_future_copy", sa.Boolean(), nullable=False), sa.Column("requires_verification", sa.Boolean(), nullable=False), sa.Column("risk_flag", sa.String(255), nullable=True), sa.Column("supporting_urls_json", sa.JSON(), nullable=True), sa.Column("supporting_candidate_evidence_ids_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("phase4_manual_review_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("review_type", sa.String(80), nullable=False), sa.Column("severity", sa.String(40), nullable=False), sa.Column("reason", sa.String(500), nullable=False), sa.Column("recommended_action", sa.String(500), nullable=True), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("claim_permissions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("verification_run_id", sa.Integer(), sa.ForeignKey("verification_runs.id"), nullable=False), sa.Column("claim_type", sa.String(120), nullable=False), sa.Column("allowed", sa.Boolean(), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("approved_phrasing", sa.String(500), nullable=True), sa.Column("blocked_phrasing_json", sa.JSON(), nullable=True), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))


def downgrade() -> None:
    for table in ["claim_permissions", "phase4_manual_review_items", "verified_personalization_evidence", "phase4_candidate_decisions", "candidate_contact_verifications", "contact_candidates", "candidate_web_presence_verifications", "url_probe_results", "search_results", "search_queries", "verification_runs"]:
        op.drop_table(table)
