"""phase10 controlled sending

Revision ID: 20260525_0010
Revises: 20260525_0009
Create Date: 2026-05-25
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260525_0010"
down_revision: str | None = "20260525_0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table("send_queue_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("run_id", sa.String(80), nullable=False, unique=True), sa.Column("campaign_id", sa.Integer(), sa.ForeignKey("campaigns.id"), nullable=False), sa.Column("operation", sa.String(80), nullable=False), sa.Column("status", sa.String(80), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("input_approved_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("queued_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("blocked_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("send_attempted_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("sent_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("started_at", sa.DateTime(timezone=True), nullable=True), sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("sender_provider_configs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("provider_slug", sa.String(120), nullable=False, unique=True), sa.Column("provider_type", sa.String(80), nullable=False), sa.Column("from_email", sa.String(255), nullable=False), sa.Column("from_name", sa.String(255), nullable=False), sa.Column("reply_to_email", sa.String(255), nullable=False), sa.Column("domain", sa.String(255), nullable=False), sa.Column("status", sa.String(80), nullable=False), sa.Column("daily_limit", sa.Integer(), nullable=False, server_default="10"), sa.Column("per_run_limit", sa.Integer(), nullable=False, server_default="5"), sa.Column("per_domain_daily_limit", sa.Integer(), nullable=False, server_default="1"), sa.Column("warmup_mode", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("warmup_stage", sa.String(40), nullable=False), sa.Column("spf_status", sa.String(80), nullable=True), sa.Column("dkim_status", sa.String(80), nullable=True), sa.Column("dmarc_status", sa.String(80), nullable=True), sa.Column("reply_to_status", sa.String(80), nullable=True), sa.Column("bounce_handling_mode", sa.String(80), nullable=True), sa.Column("notes_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("provider_circuit_breakers", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("provider_slug", sa.String(120), nullable=False), sa.Column("consecutive_failure_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("circuit_status", sa.String(40), nullable=False), sa.Column("disabled_reason", sa.String(500), nullable=True), sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True), sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("email_send_queue", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("send_queue_run_id", sa.Integer(), sa.ForeignKey("send_queue_runs.id"), nullable=False), sa.Column("campaign_id", sa.Integer(), sa.ForeignKey("campaigns.id"), nullable=False), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("phase9_decision_id", sa.Integer(), sa.ForeignKey("phase9_candidate_decisions.id"), nullable=False), sa.Column("email_draft_variant_id", sa.Integer(), sa.ForeignKey("email_draft_variants.id"), nullable=False), sa.Column("email_manual_edit_version_id", sa.Integer(), sa.ForeignKey("email_manual_edit_versions.id"), nullable=True), sa.Column("recipient_email", sa.String(255), nullable=False), sa.Column("recipient_domain", sa.String(255), nullable=False), sa.Column("sender_profile_id", sa.Integer(), sa.ForeignKey("sender_provider_configs.id"), nullable=False), sa.Column("unsubscribe_token_id", sa.Integer(), nullable=True), sa.Column("idempotency_key", sa.String(255), nullable=False), sa.Column("queue_status", sa.String(120), nullable=False), sa.Column("priority_tier", sa.String(80), nullable=True), sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True), sa.Column("claimed_by", sa.String(120), nullable=True), sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True), sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True), sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("max_retries", sa.Integer(), nullable=False, server_default="1"), sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True), sa.Column("permanent_failure", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("hold_reason", sa.String(500), nullable=True), sa.Column("cancel_reason", sa.String(500), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True), sa.UniqueConstraint("idempotency_key", name="uq_send_queue_idempotency"))
    op.create_table("unsubscribe_tokens", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("token_hash", sa.String(128), nullable=False, unique=True), sa.Column("campaign_id", sa.Integer(), sa.ForeignKey("campaigns.id"), nullable=False), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("recipient_email", sa.String(255), nullable=False), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=True), sa.Column("status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True), sa.Column("used_at", sa.DateTime(timezone=True), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True))
    op.create_table("send_queue_locks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=False), sa.Column("lock_owner", sa.String(120), nullable=False), sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("released_at", sa.DateTime(timezone=True), nullable=True), sa.Column("status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("email_send_attempts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=False), sa.Column("provider_type", sa.String(80), nullable=False), sa.Column("provider_message_id", sa.String(255), nullable=True), sa.Column("smtp_response_code", sa.String(80), nullable=True), sa.Column("provider_status", sa.String(80), nullable=False), sa.Column("attempt_status", sa.String(80), nullable=False), sa.Column("attempt_number", sa.Integer(), nullable=False), sa.Column("error_type", sa.String(120), nullable=True), sa.Column("error_message", sa.String(500), nullable=True), sa.Column("transient_error", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("permanent_error", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("unsubscribe_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("unsubscribe_token_id", sa.Integer(), sa.ForeignKey("unsubscribe_tokens.id"), nullable=True), sa.Column("recipient_email", sa.String(255), nullable=False), sa.Column("campaign_id", sa.Integer(), sa.ForeignKey("campaigns.id"), nullable=True), sa.Column("event_source", sa.String(80), nullable=False), sa.Column("ip_address", sa.String(80), nullable=True), sa.Column("user_agent", sa.String(500), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("delivery_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email_send_attempt_id", sa.Integer(), sa.ForeignKey("email_send_attempts.id"), nullable=True), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=True), sa.Column("provider_type", sa.String(80), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("provider_message_id", sa.String(255), nullable=True), sa.Column("recipient_email", sa.String(255), nullable=False), sa.Column("raw_payload_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("send_suppression_checks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=False), sa.Column("recipient_email", sa.String(255), nullable=False), sa.Column("recipient_domain", sa.String(255), nullable=False), sa.Column("suppression_hit", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("suppression_reason", sa.String(120), nullable=True), sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("send_limit_counters", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("counter_key", sa.String(255), nullable=False, unique=True), sa.Column("counter_type", sa.String(80), nullable=False), sa.Column("count", sa.Integer(), nullable=False, server_default="0"), sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("window_ends_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("message_send_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=False), sa.Column("final_subject_snapshot", sa.String(255), nullable=False), sa.Column("final_body_snapshot", sa.Text(), nullable=False), sa.Column("unsubscribe_url_snapshot", sa.String(1000), nullable=False), sa.Column("sender_snapshot_json", sa.JSON(), nullable=False), sa.Column("recipient_snapshot_json", sa.JSON(), nullable=False), sa.Column("subject_hash", sa.String(128), nullable=False), sa.Column("body_hash", sa.String(128), nullable=False), sa.Column("unsubscribe_url_hash", sa.String(128), nullable=False), sa.Column("final_message_hash", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("phase10_candidate_decisions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("candidate_business_id", sa.Integer(), sa.ForeignKey("candidate_businesses.id"), nullable=False), sa.Column("send_queue_run_id", sa.Integer(), sa.ForeignKey("send_queue_runs.id"), nullable=False), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=True), sa.Column("decision", sa.String(120), nullable=False), sa.Column("sent", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("blocked", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("reason", sa.String(500), nullable=False), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("send_audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email_send_queue_id", sa.Integer(), sa.ForeignKey("email_send_queue.id"), nullable=True), sa.Column("actor", sa.String(120), nullable=False), sa.Column("action", sa.String(80), nullable=False), sa.Column("before_json", sa.JSON(), nullable=True), sa.Column("after_json", sa.JSON(), nullable=True), sa.Column("reason", sa.String(500), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    op.create_table("suppression_import_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("run_id", sa.String(80), nullable=False, unique=True), sa.Column("file_name", sa.String(500), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("total_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("valid_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("invalid_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("imported_rows", sa.Integer(), nullable=False, server_default="0"), sa.Column("status", sa.String(80), nullable=False), sa.Column("errors_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    for table in [
        "suppression_import_runs", "send_audit_events", "phase10_candidate_decisions",
        "message_send_snapshots", "send_limit_counters", "send_suppression_checks",
        "delivery_events", "unsubscribe_events", "email_send_attempts", "send_queue_locks",
        "unsubscribe_tokens", "email_send_queue", "provider_circuit_breakers",
        "sender_provider_configs", "send_queue_runs",
    ]:
        op.drop_table(table)
