"""phase5 scoring

Revision ID: 20260525_0005
Revises: 20260525_0004
Create Date: 2026-05-25
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260525_0005"
down_revision: str | None = "20260525_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table("scoring_runs", sa.Column("id", sa.Integer(), nullable=False), sa.Column("run_id", sa.String(length=80), nullable=False), sa.Column("campaign_id", sa.Integer(), nullable=False), sa.Column("operation", sa.Enum("LEAD_SCORING", "CAMPAIGN_SELECTION", "PRIORITY_QUEUE_BUILD", "PILOT_BATCH_SELECTION", name="scoringrunoperation", native_enum=False), nullable=False), sa.Column("status", sa.Enum("STARTED", "COMPLETED", "COMPLETED_WITH_WARNINGS", "FAILED", "DRY_RUN_ONLY", "BLOCKED_BY_MISSING_VERIFICATION", "BLOCKED_BY_COMPLIANCE_RISK", name="scoringrunstatus", native_enum=False), nullable=False), sa.Column("dry_run", sa.Boolean(), nullable=False), sa.Column("scoring_profile", sa.String(length=120), nullable=False), sa.Column("score_version", sa.String(length=40), nullable=False), sa.Column("input_candidate_count", sa.Integer(), nullable=False), sa.Column("scored_count", sa.Integer(), nullable=False), sa.Column("ready_count", sa.Integer(), nullable=False), sa.Column("manual_review_count", sa.Integer(), nullable=False), sa.Column("hold_count", sa.Integer(), nullable=False), sa.Column("rejected_count", sa.Integer(), nullable=False), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("finished_at", sa.DateTime(), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("run_id"))
    op.create_table("scoring_profile_snapshots", sa.Column("id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("scoring_profile", sa.String(length=120), nullable=False), sa.Column("score_version", sa.String(length=40), nullable=False), sa.Column("formula_json", sa.JSON(), nullable=False), sa.Column("gate_policy_json", sa.JSON(), nullable=False), sa.Column("campaign_lane_policy_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("candidate_lead_scores", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("overall_lead_score", sa.Float(), nullable=False), sa.Column("website_opportunity_score", sa.Float(), nullable=False), sa.Column("business_fit_score", sa.Float(), nullable=False), sa.Column("contact_readiness_score", sa.Float(), nullable=False), sa.Column("personalization_potential_score", sa.Float(), nullable=False), sa.Column("compliance_safety_score", sa.Float(), nullable=False), sa.Column("reply_probability_band", sa.Enum("LOW", "MEDIUM", "HIGH", name="replyprobabilityband", native_enum=False), nullable=False), sa.Column("risk_penalty", sa.Float(), nullable=False), sa.Column("score_version", sa.String(length=40), nullable=False), sa.Column("scoring_profile", sa.String(length=120), nullable=False), sa.Column("positive_reasons_json", sa.JSON(), nullable=False), sa.Column("negative_reasons_json", sa.JSON(), nullable=False), sa.Column("score_reasons_json", sa.JSON(), nullable=False), sa.Column("risk_flags_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("campaign_fit_assessments", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("campaign_lane", sa.Enum("NO_WEBSITE", "SOCIAL_ONLY", "DIRECTORY_ONLY", "WEAK_WEBSITE", "NO_SAFE_CONTACT", "FUTURE_CAMPAIGN", "OUT_OF_SCOPE", name="campaignlane", native_enum=False), nullable=False), sa.Column("campaign_fit_score", sa.Float(), nullable=False), sa.Column("campaign_fit_status", sa.Enum("FIT", "FIT_WITH_WARNINGS", "NOT_FIT", "HOLD", "MANUAL_REVIEW", name="campaignfitstatus", native_enum=False), nullable=False), sa.Column("decision_reason", sa.String(length=500), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("outreach_readiness_gates", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("gate_name", sa.Enum("VERIFIED_WEB_PRESENCE_GATE", "SAFE_CONTACT_GATE", "CLAIM_PERMISSION_GATE", "PERSONALIZATION_EVIDENCE_GATE", "COMPLIANCE_SAFETY_GATE", "MANUAL_REVIEW_CLEAR_GATE", "CAMPAIGN_SCOPE_GATE", "IDENTITY_CONFIDENCE_GATE", "SUPPRESSION_COOLDOWN_GATE", name="readinessgatename", native_enum=False), nullable=False), sa.Column("passed", sa.Boolean(), nullable=False), sa.Column("severity", sa.Enum("INFO", "WARNING", "BLOCKER", name="gateseverity", native_enum=False), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("phase5_candidate_decisions", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("decision", sa.Enum("READY_FOR_PHASE_6_INSIGHT", "READY_FOR_PHASE_6_WITH_WARNINGS", "NEEDS_MANUAL_REVIEW", "HOLD_FOR_FUTURE_WEAK_WEBSITE_CAMPAIGN", "HOLD_NO_SAFE_CONTACT", "HOLD_SUPPRESSED_CONTACT", "REJECT_LOW_FIT", "REJECT_HIGH_COMPLIANCE_RISK", "REJECT_WEBSITE_ALREADY_STRONG", "REJECT_INSUFFICIENT_PERSONALIZATION_EVIDENCE", "REJECT_OUT_OF_SCOPE", name="phase5decision", native_enum=False), nullable=False), sa.Column("priority_tier", sa.Enum("P1_BEST_PILOT", "P2_GOOD_WITH_CAUTION", "P3_HOLD_LATER", "P4_MANUAL_REVIEW", "P5_REJECTED", name="prioritytier", native_enum=False), nullable=False), sa.Column("ready_for_phase6", sa.Boolean(), nullable=False), sa.Column("manual_review_required", sa.Boolean(), nullable=False), sa.Column("hold_reason", sa.String(length=500), nullable=True), sa.Column("reject_reason", sa.String(length=500), nullable=True), sa.Column("warnings_json", sa.JSON(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"))
    op.create_table("pilot_batch_candidates", sa.Column("id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("batch_name", sa.String(length=255), nullable=False), sa.Column("batch_rank", sa.Integer(), nullable=False), sa.Column("priority_tier", sa.Enum("P1_BEST_PILOT", "P2_GOOD_WITH_CAUTION", "P3_HOLD_LATER", "P4_MANUAL_REVIEW", "P5_REJECTED", name="prioritytier", native_enum=False), nullable=False), sa.Column("campaign_lane", sa.Enum("NO_WEBSITE", "SOCIAL_ONLY", "DIRECTORY_ONLY", "WEAK_WEBSITE", "NO_SAFE_CONTACT", "FUTURE_CAMPAIGN", "OUT_OF_SCOPE", name="campaignlane", native_enum=False), nullable=False), sa.Column("selection_reason", sa.String(length=500), nullable=False), sa.Column("selected", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("batch_name", "candidate_business_id"))
    op.create_table("scoring_manual_review_items", sa.Column("id", sa.Integer(), nullable=False), sa.Column("candidate_business_id", sa.Integer(), nullable=False), sa.Column("scoring_run_id", sa.Integer(), nullable=False), sa.Column("review_type", sa.Enum("LOW_PERSONALIZATION_EVIDENCE", "CLAIM_PERMISSION_MISSING", "CONTACT_PERMISSION_UNCLEAR", "HIGH_COMPLIANCE_RISK", "CAMPAIGN_FIT_AMBIGUOUS", "WEBSITE_STATUS_CONFLICT", "CATEGORY_SCOPE_ISSUE", "SUPPRESSION_OR_COOLDOWN", "SCORING_DATA_INCOMPLETE", name="scoringreviewtype", native_enum=False), nullable=False), sa.Column("severity", sa.String(length=40), nullable=False), sa.Column("reason", sa.String(length=500), nullable=False), sa.Column("recommended_action", sa.String(length=500), nullable=False), sa.Column("evidence_json", sa.JSON(), nullable=False), sa.Column("status", sa.Enum("OPEN", "RESOLVED", "IGNORED", name="manualreviewstatus", native_enum=False), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.ForeignKeyConstraint(["candidate_business_id"], ["candidate_businesses.id"]), sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    op.drop_table("scoring_manual_review_items")
    op.drop_table("pilot_batch_candidates")
    op.drop_table("phase5_candidate_decisions")
    op.drop_table("outreach_readiness_gates")
    op.drop_table("campaign_fit_assessments")
    op.drop_table("candidate_lead_scores")
    op.drop_table("scoring_profile_snapshots")
    op.drop_table("scoring_runs")
