from enum import StrEnum


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    LOCKED = "LOCKED"


class LeadStatus(StrEnum):
    RAW = "RAW"
    NORMALIZED = "NORMALIZED"
    NEEDS_VERIFICATION = "NEEDS_VERIFICATION"
    VERIFIED = "VERIFIED"
    READY_FOR_SCORING = "READY_FOR_SCORING"
    READY_FOR_DRAFT = "READY_FOR_DRAFT"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    REJECTED = "REJECTED"
    CONTACTED = "CONTACTED"
    RESPONDED = "RESPONDED"
    WON = "WON"
    LOST = "LOST"
    SUPPRESSED = "SUPPRESSED"


class SourceName(StrEnum):
    GEOAPIFY = "geoapify"
    OSM_OVERPASS = "osm_overpass"
    NZBN = "nzbn"
    TAVILY = "tavily"
    MANUAL = "manual"
    FIXTURE = "fixture"


class EmailType(StrEnum):
    GENERIC_BUSINESS = "GENERIC_BUSINESS"
    ROLE_BASED = "ROLE_BASED"
    PERSONAL = "PERSONAL"
    UNKNOWN = "UNKNOWN"


class WebsiteStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    NO_WEBSITE_PROBABLE = "NO_WEBSITE_PROBABLE"
    NO_WEBSITE_CONFIRMED = "NO_WEBSITE_CONFIRMED"
    WEBSITE_FOUND = "WEBSITE_FOUND"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    WEAK_WEBSITE = "WEAK_WEBSITE"


class LeadScoreDecision(StrEnum):
    READY_FOR_DRAFT = "READY_FOR_DRAFT"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    REJECT_LOW_FIT = "REJECT_LOW_FIT"
    REJECT_WEBSITE_FOUND = "REJECT_WEBSITE_FOUND"
    REJECT_NO_CONTACT = "REJECT_NO_CONTACT"
    REJECT_COMPLIANCE_RISK = "REJECT_COMPLIANCE_RISK"


class EmailDraftStatus(StrEnum):
    DRAFT_CREATED = "DRAFT_CREATED"
    JUDGE_PENDING = "JUDGE_PENDING"
    APPROVED = "APPROVED"
    REWRITE_REQUIRED = "REWRITE_REQUIRED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    BLOCKED = "BLOCKED"


class JudgementDecision(StrEnum):
    APPROVED = "APPROVED"
    REWRITE_REQUIRED = "REWRITE_REQUIRED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    BLOCKED = "BLOCKED"


class EmailSendStatus(StrEnum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED_TO_SEND = "APPROVED_TO_SEND"
    BLOCKED_BY_SAFETY_FLAG = "BLOCKED_BY_SAFETY_FLAG"
    BLOCKED_BY_SUPPRESSION = "BLOCKED_BY_SUPPRESSION"
    BLOCKED_BY_DAILY_LIMIT = "BLOCKED_BY_DAILY_LIMIT"
    SENT = "SENT"
    FAILED = "FAILED"


class SuppressionReason(StrEnum):
    UNSUBSCRIBED = "UNSUBSCRIBED"
    BOUNCED = "BOUNCED"
    COMPLAINT = "COMPLAINT"
    MANUAL_BLOCK = "MANUAL_BLOCK"
    LEGAL_RISK = "LEGAL_RISK"


class Actor(StrEnum):
    SYSTEM = "system"
    CLI = "cli"
    API = "api"
    OPERATOR = "operator"
    WORKER = "worker"
    TEST = "test"


class SensitiveOperation(StrEnum):
    LIVE_API_CALL = "live_api_call"
    LEAD_COLLECTION = "lead_collection"
    AI_GENERATION = "ai_generation"
    EMAIL_DRAFTING = "email_drafting"
    EMAIL_SENDING = "email_sending"
    FOLLOWUP_SENDING = "followup_sending"
    VOICE_CALL = "voice_call"
    GOOGLE_MAPS_USAGE = "google_maps_usage"
    PUBLIC_DASHBOARD = "public_dashboard"


class SourceRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_CONFIG = "BLOCKED_BY_CONFIG"
    BLOCKED_BY_SOURCE_BUDGET = "BLOCKED_BY_SOURCE_BUDGET"


class SourceOperation(StrEnum):
    COLLECT_PLACES = "collect_places"
    COLLECT_OSM = "collect_osm"
    ENRICH_NZBN = "enrich_nzbn"
    SOURCE_CHECK = "source_check"


class RawRecordType(StrEnum):
    PLACE = "place"
    BUSINESS_ENTITY = "business_entity"
    OSM_NODE = "osm_node"
    OSM_WAY = "osm_way"
    OSM_RELATION = "osm_relation"
    FIXTURE = "fixture"


class CandidateStatus(StrEnum):
    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    READY_FOR_WEBSITE_VERIFICATION = "READY_FOR_WEBSITE_VERIFICATION"
    REJECTED_DUPLICATE = "REJECTED_DUPLICATE"
    REJECTED_LOW_QUALITY = "REJECTED_LOW_QUALITY"
    REJECTED_CHAIN_OR_FRANCHISE = "REJECTED_CHAIN_OR_FRANCHISE"
    REJECTED_OUT_OF_SCOPE = "REJECTED_OUT_OF_SCOPE"


class VerificationReadiness(StrEnum):
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    NOT_READY_MISSING_NAME = "NOT_READY_MISSING_NAME"
    NOT_READY_MISSING_LOCATION = "NOT_READY_MISSING_LOCATION"
    NOT_READY_AMBIGUOUS_IDENTITY = "NOT_READY_AMBIGUOUS_IDENTITY"
    NOT_READY_DUPLICATE_RISK = "NOT_READY_DUPLICATE_RISK"
    NOT_READY_CHAIN_RISK = "NOT_READY_CHAIN_RISK"
    NOT_READY_LOW_QUALITY = "NOT_READY_LOW_QUALITY"


class CandidateSourceLinkType(StrEnum):
    PRIMARY_SOURCE = "PRIMARY_SOURCE"
    SUPPORTING_SOURCE = "SUPPORTING_SOURCE"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    REJECTED_MATCH = "REJECTED_MATCH"
    NZBN_ENTITY_HINT = "NZBN_ENTITY_HINT"


class CandidateQualityDecision(StrEnum):
    READY_FOR_PHASE_4 = "READY_FOR_PHASE_4"
    READY_FOR_PHASE_4_WITH_WARNINGS = "READY_FOR_PHASE_4_WITH_WARNINGS"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
    REJECT = "REJECT"


class NormalizationOperation(StrEnum):
    NORMALIZE_RAW_RECORDS = "normalize_raw_records"
    DEDUPE_CANDIDATES = "dedupe_candidates"
    REBUILD_CANDIDATES = "rebuild_candidates"
    QUALITY_REVIEW = "quality_review"
    CANDIDATE_EVIDENCE_CONSOLIDATION = "candidate_evidence_consolidation"


class NormalizationRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"


class DuplicateClusterStatus(StrEnum):
    AUTO_MERGED = "AUTO_MERGED"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    REJECTED_NOT_DUPLICATE = "REJECTED_NOT_DUPLICATE"
    SPLIT_REQUIRED = "SPLIT_REQUIRED"


class ManualReviewType(StrEnum):
    AMBIGUOUS_DUPLICATE = "AMBIGUOUS_DUPLICATE"
    CHAIN_RISK = "CHAIN_RISK"
    BRANCH_RISK = "BRANCH_RISK"
    LOW_IDENTITY_CONFIDENCE = "LOW_IDENTITY_CONFIDENCE"
    LOCATION_CONFLICT = "LOCATION_CONFLICT"
    CATEGORY_CONFLICT = "CATEGORY_CONFLICT"
    MULTI_SOURCE_CONFLICT = "MULTI_SOURCE_CONFLICT"
    GENERIC_NAME_RISK = "GENERIC_NAME_RISK"
    NZBN_MISMATCH = "NZBN_MISMATCH"
    LOW_DATA_QUALITY = "LOW_DATA_QUALITY"


class ManualReviewStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"


class ConflictType(StrEnum):
    NAME_CONFLICT = "NAME_CONFLICT"
    LOCATION_CONFLICT = "LOCATION_CONFLICT"
    CATEGORY_CONFLICT = "CATEGORY_CONFLICT"
    PHONE_SHARED_ACROSS_CANDIDATES = "PHONE_SHARED_ACROSS_CANDIDATES"
    WEBSITE_SHARED_ACROSS_CANDIDATES = "WEBSITE_SHARED_ACROSS_CANDIDATES"
    NZBN_ENTITY_MISMATCH = "NZBN_ENTITY_MISMATCH"
    POSSIBLE_BRANCH_SPLIT = "POSSIBLE_BRANCH_SPLIT"


class VerificationRunOperation(StrEnum):
    WEBSITE_VERIFICATION = "website_verification"
    CONTACT_VERIFICATION = "contact_verification"
    WEB_PRESENCE_CLASSIFICATION = "web_presence_classification"
    PHASE4_FULL_REVIEW = "phase4_full_review"


class VerificationRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    BLOCKED_BY_CONFIG = "BLOCKED_BY_CONFIG"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_BUDGET = "BLOCKED_BY_BUDGET"


class SearchQueryType(StrEnum):
    OFFICIAL_WEBSITE_SEARCH = "official_website_search"
    CONTACT_SEARCH = "contact_search"
    SOCIAL_SEARCH = "social_search"
    BOOKING_SEARCH = "booking_search"
    BRAND_DISAMBIGUATION_SEARCH = "brand_disambiguation_search"
    DIRECTORY_SEARCH = "directory_search"


class SearchQueryStatus(StrEnum):
    PLANNED = "PLANNED"
    CACHE_HIT = "CACHE_HIT"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    BLOCKED_BY_BUDGET = "BLOCKED_BY_BUDGET"
    SKIPPED_DRY_RUN = "SKIPPED_DRY_RUN"


class SearchResultType(StrEnum):
    POSSIBLE_OFFICIAL_WEBSITE = "possible_official_website"
    SOCIAL_PROFILE = "social_profile"
    DIRECTORY_LISTING = "directory_listing"
    BOOKING_PAGE = "booking_page"
    MARKETPLACE_PAGE = "marketplace_page"
    IRRELEVANT = "irrelevant"
    UNKNOWN = "unknown"


class DomainClassification(StrEnum):
    OFFICIAL_CANDIDATE_DOMAIN = "official_candidate_domain"
    SOCIAL_DOMAIN = "social_domain"
    DIRECTORY_DOMAIN = "directory_domain"
    BOOKING_PLATFORM_DOMAIN = "booking_platform_domain"
    MARKETPLACE_DOMAIN = "marketplace_domain"
    PARKED_DOMAIN = "parked_domain"
    IRRELEVANT_DOMAIN = "irrelevant_domain"
    SUSPICIOUS_DOMAIN = "suspicious_domain"
    UNKNOWN_DOMAIN = "unknown_domain"


class UrlProbeStatus(StrEnum):
    OK = "OK"
    TIMEOUT = "TIMEOUT"
    TLS_ERROR = "TLS_ERROR"
    DNS_ERROR = "DNS_ERROR"
    BLOCKED = "BLOCKED"
    NON_HTML = "NON_HTML"
    FAILED = "FAILED"
    SKIPPED_DRY_RUN = "SKIPPED_DRY_RUN"
    SKIPPED_BY_POLICY = "SKIPPED_BY_POLICY"


class Phase4WebsiteStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    NO_WEBSITE_PROBABLE = "NO_WEBSITE_PROBABLE"
    NO_WEBSITE_CONFIRMED = "NO_WEBSITE_CONFIRMED"
    WEBSITE_FOUND_OFFICIAL = "WEBSITE_FOUND_OFFICIAL"
    WEBSITE_FOUND_UNCLEAR = "WEBSITE_FOUND_UNCLEAR"
    WEAK_WEBSITE_FOUND = "WEAK_WEBSITE_FOUND"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    DIRECTORY_ONLY = "DIRECTORY_ONLY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class ContactType(StrEnum):
    EMAIL = "email"
    PHONE = "phone"
    CONTACT_FORM = "contact_form"
    SOCIAL_DM = "social_dm"
    BOOKING_LINK = "booking_link"


class ContactSourceType(StrEnum):
    OFFICIAL_WEBSITE = "official_website"
    SOCIAL_PROFILE = "social_profile"
    DIRECTORY_LISTING = "directory_listing"
    RAW_SOURCE = "raw_source"
    SEARCH_RESULT = "search_result"
    UNKNOWN = "unknown"


class ContactRiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKED = "BLOCKED"


class ContactStatus(StrEnum):
    NO_CONTACT_FOUND = "NO_CONTACT_FOUND"
    GENERIC_BUSINESS_EMAIL_FOUND = "GENERIC_BUSINESS_EMAIL_FOUND"
    ROLE_BASED_EMAIL_FOUND = "ROLE_BASED_EMAIL_FOUND"
    PERSONAL_EMAIL_FOUND_BLOCKED = "PERSONAL_EMAIL_FOUND_BLOCKED"
    CONTACT_FORM_FOUND = "CONTACT_FORM_FOUND"
    SOCIAL_ONLY_CONTACT = "SOCIAL_ONLY_CONTACT"
    PHONE_ONLY = "PHONE_ONLY"
    CONTACT_RISKY = "CONTACT_RISKY"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class Phase4Decision(StrEnum):
    READY_FOR_PHASE_5_SCORING = "READY_FOR_PHASE_5_SCORING"
    READY_FOR_PHASE_5_WITH_WARNINGS = "READY_FOR_PHASE_5_WITH_WARNINGS"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    REJECT_WEBSITE_ALREADY_STRONG = "REJECT_WEBSITE_ALREADY_STRONG"
    REJECT_INSUFFICIENT_EVIDENCE = "REJECT_INSUFFICIENT_EVIDENCE"
    REJECT_COMPLIANCE_RISK = "REJECT_COMPLIANCE_RISK"
    REJECT_OUT_OF_SCOPE = "REJECT_OUT_OF_SCOPE"


class Phase4ReviewType(StrEnum):
    UNCLEAR_WEBSITE_OWNERSHIP = "UNCLEAR_WEBSITE_OWNERSHIP"
    NOISY_SEARCH_RESULTS = "NOISY_SEARCH_RESULTS"
    GENERIC_BUSINESS_NAME = "GENERIC_BUSINESS_NAME"
    POSSIBLE_BRANCH_OR_CHAIN = "POSSIBLE_BRANCH_OR_CHAIN"
    OFFICIAL_WEBSITE_LOCATION_MISMATCH = "OFFICIAL_WEBSITE_LOCATION_MISMATCH"
    CONTACT_EMAIL_PERSONAL = "CONTACT_EMAIL_PERSONAL"
    CONTACT_DOMAIN_MISMATCH = "CONTACT_DOMAIN_MISMATCH"
    ONLY_DIRECTORY_CONTACT_FOUND = "ONLY_DIRECTORY_CONTACT_FOUND"
    ONLY_SOCIAL_FOUND_LOW_CONFIDENCE = "ONLY_SOCIAL_FOUND_LOW_CONFIDENCE"
    WEBSITE_FOUND_BUT_BROKEN = "WEBSITE_FOUND_BUT_BROKEN"
    WEBSITE_FOUND_STRONG_REJECT = "WEBSITE_FOUND_STRONG_REJECT"
    INSUFFICIENT_SEARCH_DIVERSITY = "INSUFFICIENT_SEARCH_DIVERSITY"
    COMPLIANCE_RISK = "COMPLIANCE_RISK"


class ScoringRunOperation(StrEnum):
    LEAD_SCORING = "lead_scoring"
    CAMPAIGN_SELECTION = "campaign_selection"
    PRIORITY_QUEUE_BUILD = "priority_queue_build"
    PILOT_BATCH_SELECTION = "pilot_batch_selection"


class ScoringRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_MISSING_VERIFICATION = "BLOCKED_BY_MISSING_VERIFICATION"
    BLOCKED_BY_COMPLIANCE_RISK = "BLOCKED_BY_COMPLIANCE_RISK"


class ReplyProbabilityBand(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class CampaignLane(StrEnum):
    NO_WEBSITE = "NO_WEBSITE"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    DIRECTORY_ONLY = "DIRECTORY_ONLY"
    WEAK_WEBSITE = "WEAK_WEBSITE"
    NO_SAFE_CONTACT = "NO_SAFE_CONTACT"
    FUTURE_CAMPAIGN = "FUTURE_CAMPAIGN"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class CampaignFitStatus(StrEnum):
    FIT = "FIT"
    FIT_WITH_WARNINGS = "FIT_WITH_WARNINGS"
    NOT_FIT = "NOT_FIT"
    HOLD = "HOLD"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ReadinessGateName(StrEnum):
    VERIFIED_WEB_PRESENCE_GATE = "verified_web_presence_gate"
    SAFE_CONTACT_GATE = "safe_contact_gate"
    CLAIM_PERMISSION_GATE = "claim_permission_gate"
    PERSONALIZATION_EVIDENCE_GATE = "personalization_evidence_gate"
    COMPLIANCE_SAFETY_GATE = "compliance_safety_gate"
    MANUAL_REVIEW_CLEAR_GATE = "manual_review_clear_gate"
    CAMPAIGN_SCOPE_GATE = "campaign_scope_gate"
    IDENTITY_CONFIDENCE_GATE = "identity_confidence_gate"
    SUPPRESSION_COOLDOWN_GATE = "suppression_cooldown_gate"


class GateSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKER = "BLOCKER"


class Phase5Decision(StrEnum):
    READY_FOR_PHASE_6_INSIGHT = "READY_FOR_PHASE_6_INSIGHT"
    READY_FOR_PHASE_6_WITH_WARNINGS = "READY_FOR_PHASE_6_WITH_WARNINGS"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    HOLD_FOR_FUTURE_WEAK_WEBSITE_CAMPAIGN = "HOLD_FOR_FUTURE_WEAK_WEBSITE_CAMPAIGN"
    HOLD_NO_SAFE_CONTACT = "HOLD_NO_SAFE_CONTACT"
    HOLD_SUPPRESSED_CONTACT = "HOLD_SUPPRESSED_CONTACT"
    REJECT_LOW_FIT = "REJECT_LOW_FIT"
    REJECT_HIGH_COMPLIANCE_RISK = "REJECT_HIGH_COMPLIANCE_RISK"
    REJECT_WEBSITE_ALREADY_STRONG = "REJECT_WEBSITE_ALREADY_STRONG"
    REJECT_INSUFFICIENT_PERSONALIZATION_EVIDENCE = "REJECT_INSUFFICIENT_PERSONALIZATION_EVIDENCE"
    REJECT_OUT_OF_SCOPE = "REJECT_OUT_OF_SCOPE"


class PriorityTier(StrEnum):
    P1_BEST_PILOT = "P1_BEST_PILOT"
    P2_GOOD_WITH_CAUTION = "P2_GOOD_WITH_CAUTION"
    P3_HOLD_LATER = "P3_HOLD_LATER"
    P4_MANUAL_REVIEW = "P4_MANUAL_REVIEW"
    P5_REJECTED = "P5_REJECTED"


class ScoringReviewType(StrEnum):
    LOW_PERSONALIZATION_EVIDENCE = "LOW_PERSONALIZATION_EVIDENCE"
    CLAIM_PERMISSION_MISSING = "CLAIM_PERMISSION_MISSING"
    CONTACT_PERMISSION_UNCLEAR = "CONTACT_PERMISSION_UNCLEAR"
    HIGH_COMPLIANCE_RISK = "HIGH_COMPLIANCE_RISK"
    CAMPAIGN_FIT_AMBIGUOUS = "CAMPAIGN_FIT_AMBIGUOUS"
    WEBSITE_STATUS_CONFLICT = "WEBSITE_STATUS_CONFLICT"
    CATEGORY_SCOPE_ISSUE = "CATEGORY_SCOPE_ISSUE"
    SUPPRESSION_OR_COOLDOWN = "SUPPRESSION_OR_COOLDOWN"
    SCORING_DATA_INCOMPLETE = "SCORING_DATA_INCOMPLETE"


class InsightRunOperation(StrEnum):
    BUSINESS_INSIGHT_GENERATION = "business_insight_generation"
    OFFER_MATCHING = "offer_matching"
    ECONOMIC_VALUE_MAPPING = "economic_value_mapping"
    FUTURE_EMAIL_BLOCK_BUILDING = "future_email_block_building"
    PHASE6_FULL_REVIEW = "phase6_full_review"


class InsightRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_MISSING_PHASE5_DECISION = "BLOCKED_BY_MISSING_PHASE5_DECISION"
    BLOCKED_BY_MISSING_PLAYBOOK = "BLOCKED_BY_MISSING_PLAYBOOK"
    BLOCKED_BY_UNSUPPORTED_CLAIMS = "BLOCKED_BY_UNSUPPORTED_CLAIMS"


class OfferPlaybookStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DRAFT = "DRAFT"
    DISABLED = "DISABLED"


class OfferModuleType(StrEnum):
    BOOKING = "booking"
    MENU = "menu"
    QUOTE_REQUEST = "quote_request"
    GALLERY = "gallery"
    REVIEWS = "reviews"
    LOCAL_SEO = "local_seo"
    CONTACT = "contact"
    CRM = "crm"
    AUTOMATION = "automation"
    TRUST = "trust"
    CONTENT = "content"
    DIRECTIONS = "directions"
    FORMS = "forms"
    PAYMENTS_READY = "payments_ready"
    REMINDERS_READY = "reminders_ready"


class ComplexityLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class MaintenanceRisk(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class WordpressFit(StrEnum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    POSSIBLE = "POSSIBLE"
    POOR = "POOR"


class OfferPackage(StrEnum):
    STARTER_DIRECT_SITE = "STARTER_DIRECT_SITE"
    BOOKING_SYSTEM_SITE = "BOOKING_SYSTEM_SITE"
    MENU_QR_SITE = "MENU_QR_SITE"
    QUOTE_REQUEST_SITE = "QUOTE_REQUEST_SITE"
    SOCIAL_TO_OWNED_SITE = "SOCIAL_TO_OWNED_SITE"
    WEAK_WEBSITE_REFRESH = "WEAK_WEBSITE_REFRESH"
    LOCAL_TRUST_SITE = "LOCAL_TRUST_SITE"


class PainPointType(StrEnum):
    NO_DEDICATED_WEBSITE = "no_dedicated_website"
    SOCIAL_ONLY_PRESENCE = "social_only_presence"
    DIRECTORY_ONLY_PRESENCE = "directory_only_presence"
    UNCLEAR_BOOKING_PATH = "unclear_booking_path"
    UNCLEAR_SERVICE_MENU = "unclear_service_menu"
    UNCLEAR_PRICING = "unclear_pricing"
    WEAK_DIRECT_CONTACT_PATH = "weak_direct_contact_path"
    THIRD_PARTY_DEPENDENCY_RISK = "third_party_dependency_risk"
    MISSING_DIRECT_MENU = "missing_direct_menu"
    MISSING_QUOTE_FLOW = "missing_quote_flow"
    LOW_TRUST_SURFACE = "low_trust_surface"
    UNCLEAR_CUSTOMER_ACTION_PATH = "unclear_customer_action_path"


class EconomicAngleType(StrEnum):
    REDUCE_THIRD_PARTY_DEPENDENCY = "reduce_third_party_dependency"
    DIRECT_BOOKING_PATH = "direct_booking_path"
    DIRECT_MENU_OWNERSHIP = "direct_menu_ownership"
    DIRECT_QUOTE_REQUESTS = "direct_quote_requests"
    LOWER_FRICTION_CUSTOMER_ACTION = "lower_friction_customer_action"
    OWNED_BRAND_PRESENCE = "owned_brand_presence"
    SIMPLE_AFFORDABLE_START = "simple_affordable_start"
    MODULAR_UPGRADE_PATH = "modular_upgrade_path"
    DIRECT_CUSTOMER_RELATIONSHIP = "direct_customer_relationship"
    EASIER_UPDATES = "easier_updates"


class ClaimStrength(StrEnum):
    SAFE_GENERAL = "SAFE_GENERAL"
    CAUTIOUS = "CAUTIOUS"
    REQUIRES_VERIFICATION = "REQUIRES_VERIFICATION"
    BLOCKED = "BLOCKED"


class FutureEmailBlockType(StrEnum):
    OBSERVATION_BLOCK = "observation_block"
    SOFT_PROBLEM_BLOCK = "soft_problem_block"
    OFFER_MODULE_BLOCK = "offer_module_block"
    ECONOMIC_VALUE_BLOCK = "economic_value_block"
    CTA_IDEA_BLOCK = "cta_idea_block"
    BLOCKED_CLAIM_BLOCK = "blocked_claim_block"


class OfferReadinessGateName(StrEnum):
    CATEGORY_PLAYBOOK_EXISTS_GATE = "category_playbook_exists_gate"
    OFFER_FIT_GATE = "offer_fit_gate"
    ECONOMIC_CLAIM_SAFETY_GATE = "economic_claim_safety_gate"
    PERSONALIZATION_SUPPORT_GATE = "personalization_support_gate"
    MODULE_RELEVANCE_GATE = "module_relevance_gate"
    NON_PROMOTIONAL_ANGLE_GATE = "non_promotional_angle_gate"
    PHASE5_DECISION_GATE = "phase5_decision_gate"
    IMPLEMENTATION_FEASIBILITY_GATE = "implementation_feasibility_gate"
    PRICE_POSITIONING_GATE = "price_positioning_gate"


class PricePositioning(StrEnum):
    AFFORDABLE_STARTER_PACKAGE = "affordable_starter_package"
    MODULAR_LOW_RISK_START = "modular_low_risk_start"
    PREMIUM_CUSTOM_SOLUTION = "premium_custom_solution"
    AVOID_PRICE_IN_FIRST_EMAIL = "avoid_price_in_first_email"


class PriceVisibility(StrEnum):
    DO_NOT_MENTION = "do_not_mention"
    SOFT_MENTION = "soft_mention"
    MENTION_LATER = "mention_later"
    MANUAL_REVIEW = "manual_review"


class FeasibilityLevel(StrEnum):
    EASY = "EASY"
    MODERATE = "MODERATE"
    COMPLEX = "COMPLEX"
    NOT_RECOMMENDED_FOR_FIRST_OFFER = "NOT_RECOMMENDED_FOR_FIRST_OFFER"


class Phase6Decision(StrEnum):
    READY_FOR_PHASE_7_EMAIL_WRITER = "READY_FOR_PHASE_7_EMAIL_WRITER"
    READY_FOR_PHASE_7_WITH_WARNINGS = "READY_FOR_PHASE_7_WITH_WARNINGS"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"
    HOLD_UNCLEAR_OFFER = "HOLD_UNCLEAR_OFFER"
    HOLD_UNSUPPORTED_ECONOMIC_CLAIM = "HOLD_UNSUPPORTED_ECONOMIC_CLAIM"
    REJECT_LOW_OFFER_FIT = "REJECT_LOW_OFFER_FIT"
    REJECT_MISSING_PLAYBOOK = "REJECT_MISSING_PLAYBOOK"
    REJECT_IMPLEMENTATION_RISK_TOO_HIGH = "REJECT_IMPLEMENTATION_RISK_TOO_HIGH"


class OfferReviewType(StrEnum):
    MISSING_PLAYBOOK = "MISSING_PLAYBOOK"
    LOW_OFFER_FIT = "LOW_OFFER_FIT"
    UNSUPPORTED_ECONOMIC_CLAIM = "UNSUPPORTED_ECONOMIC_CLAIM"
    TOO_PROMOTIONAL = "TOO_PROMOTIONAL"
    INSUFFICIENT_PERSONALIZATION_SUPPORT = "INSUFFICIENT_PERSONALIZATION_SUPPORT"
    IMPLEMENTATION_RISK = "IMPLEMENTATION_RISK"
    PRICE_POSITIONING_RISK = "PRICE_POSITIONING_RISK"
    MODULE_RELEVANCE_CONFLICT = "MODULE_RELEVANCE_CONFLICT"


class EmailGenerationOperation(StrEnum):
    SUBJECT_GENERATION = "subject_generation"
    EMAIL_DRAFT_GENERATION = "email_draft_generation"
    EMAIL_VARIANT_GENERATION = "email_variant_generation"
    PHASE7_FULL_GENERATION = "phase7_full_generation"


class EmailGenerationRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_AI_CONFIG = "BLOCKED_BY_AI_CONFIG"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    BLOCKED_BY_INSUFFICIENT_EVIDENCE = "BLOCKED_BY_INSUFFICIENT_EVIDENCE"
    BLOCKED_BY_BUDGET = "BLOCKED_BY_BUDGET"


class EmailPromptTemplateStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DRAFT = "DRAFT"
    DISABLED = "DISABLED"


class EmailDraftVariantStatus(StrEnum):
    DRAFT_CREATED = "DRAFT_CREATED"
    JUDGE_PENDING = "JUDGE_PENDING"
    JUDGED = "JUDGED"
    AWAITING_REWRITE = "AWAITING_REWRITE"
    REWRITE_EXHAUSTED = "REWRITE_EXHAUSTED"
    NEEDS_MANUAL_REVIEW_BEFORE_JUDGE = "NEEDS_MANUAL_REVIEW_BEFORE_JUDGE"
    BLOCKED_PRECHECK = "BLOCKED_PRECHECK"
    FAILED_GENERATION = "FAILED_GENERATION"
    FAILED_JSON_SCHEMA = "FAILED_JSON_SCHEMA"


class EmailClaimRiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKED = "BLOCKED"


class DraftPrecheckStatus(StrEnum):
    PASSED = "PASSED"
    PASSED_WITH_WARNINGS = "PASSED_WITH_WARNINGS"
    FAILED = "FAILED"


class DraftSimilarityDecision(StrEnum):
    OK = "OK"
    WARNING_SIMILAR = "WARNING_SIMILAR"
    BLOCKED_TOO_SIMILAR = "BLOCKED_TOO_SIMILAR"


class Phase7Decision(StrEnum):
    DRAFT_CREATED_JUDGE_PENDING = "DRAFT_CREATED_JUDGE_PENDING"
    DRAFT_CREATED_WITH_WARNINGS = "DRAFT_CREATED_WITH_WARNINGS"
    NEEDS_MANUAL_REVIEW_BEFORE_JUDGE = "NEEDS_MANUAL_REVIEW_BEFORE_JUDGE"
    HOLD_INSUFFICIENT_COPY_EVIDENCE = "HOLD_INSUFFICIENT_COPY_EVIDENCE"
    BLOCKED_BY_UNSAFE_CLAIM_RISK = "BLOCKED_BY_UNSAFE_CLAIM_RISK"
    BLOCKED_BY_AI_CONFIG = "BLOCKED_BY_AI_CONFIG"
    FAILED_GENERATION = "FAILED_GENERATION"


class EmailGenerationReviewType(StrEnum):
    AI_OUTPUT_INVALID = "AI_OUTPUT_INVALID"
    DRAFT_TOO_GENERIC = "DRAFT_TOO_GENERIC"
    DRAFT_TOO_PROMOTIONAL = "DRAFT_TOO_PROMOTIONAL"
    UNSAFE_CLAIM = "UNSAFE_CLAIM"
    INSUFFICIENT_EVIDENCE_MAPPING = "INSUFFICIENT_EVIDENCE_MAPPING"
    SIMILARITY_TOO_HIGH = "SIMILARITY_TOO_HIGH"
    PROMPT_INJECTION_RISK = "PROMPT_INJECTION_RISK"
    TONE_RISK = "TONE_RISK"
    CTA_RISK = "CTA_RISK"
    ECONOMIC_CLAIM_RISK = "ECONOMIC_CLAIM_RISK"


class EmailJudgeOperation(StrEnum):
    RULE_JUDGE = "rule_judge"
    AI_QUALITY_JUDGE = "ai_quality_judge"
    PHASE8_FULL_JUDGE = "phase8_full_judge"
    VARIANT_SELECTION = "variant_selection"


class EmailJudgeRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_AI_CONFIG = "BLOCKED_BY_AI_CONFIG"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    BLOCKED_BY_NO_ELIGIBLE_DRAFTS = "BLOCKED_BY_NO_ELIGIBLE_DRAFTS"


class EmailJudgeMode(StrEnum):
    RULE_ONLY = "RULE_ONLY"
    RULE_PLUS_AI = "RULE_PLUS_AI"


class EmailAiJudgeDecision(StrEnum):
    PASS = "PASS"
    PASS_WITH_WARNINGS = "PASS_WITH_WARNINGS"
    REWRITE_REQUIRED = "REWRITE_REQUIRED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    BLOCK = "BLOCK"


class EmailJudgeFindingType(StrEnum):
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    ABSOLUTE_NO_WEBSITE_CLAIM = "ABSOLUTE_NO_WEBSITE_CLAIM"
    COMMISSION_CLAIM = "COMMISSION_CLAIM"
    GUARANTEED_RESULT_CLAIM = "GUARANTEED_RESULT_CLAIM"
    GOOGLE_MAPS_REFERENCE = "GOOGLE_MAPS_REFERENCE"
    TOO_GENERIC = "TOO_GENERIC"
    TOO_PROMOTIONAL = "TOO_PROMOTIONAL"
    CREEPY_EVIDENCE = "CREEPY_EVIDENCE"
    ECONOMIC_CLAIM_RISK = "ECONOMIC_CLAIM_RISK"
    CTA_TOO_STRONG = "CTA_TOO_STRONG"
    MULTIPLE_CTA = "MULTIPLE_CTA"
    SPAM_RISK = "SPAM_RISK"
    MISSING_UNSUBSCRIBE = "MISSING_UNSUBSCRIBE"
    MISSING_SENDER_IDENTITY = "MISSING_SENDER_IDENTITY"
    PERSONALIZATION_WEAK = "PERSONALIZATION_WEAK"
    EVIDENCE_MAPPING_MISSING = "EVIDENCE_MAPPING_MISSING"
    SIMILARITY_RISK = "SIMILARITY_RISK"
    AI_LIKE_TEMPLATE_RISK = "AI_LIKE_TEMPLATE_RISK"
    PRICE_CLAIM_RISK = "PRICE_CLAIM_RISK"
    PLATFORM_ATTACK = "PLATFORM_ATTACK"
    TONE_RISK = "TONE_RISK"


class EmailJudgeDecisionValue(StrEnum):
    APPROVED_FOR_HUMAN_REVIEW = "APPROVED_FOR_HUMAN_REVIEW"
    APPROVED_WITH_WARNINGS_FOR_HUMAN_REVIEW = "APPROVED_WITH_WARNINGS_FOR_HUMAN_REVIEW"
    REWRITE_REQUIRED = "REWRITE_REQUIRED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    BLOCKED_UNSAFE_CLAIM = "BLOCKED_UNSAFE_CLAIM"
    BLOCKED_COMPLIANCE_RISK = "BLOCKED_COMPLIANCE_RISK"
    BLOCKED_TOO_GENERIC = "BLOCKED_TOO_GENERIC"
    BLOCKED_TOO_PROMOTIONAL = "BLOCKED_TOO_PROMOTIONAL"
    BLOCKED_EVIDENCE_MISSING = "BLOCKED_EVIDENCE_MISSING"
    BLOCKED_SPAM_RISK = "BLOCKED_SPAM_RISK"
    BLOCKED_CREEPY_EVIDENCE = "BLOCKED_CREEPY_EVIDENCE"


class JudgeDisagreementResolution(StrEnum):
    RULE_BLOCKER_OVERRIDES = "RULE_BLOCKER_OVERRIDES"
    AI_REWRITE_ACCEPTED = "AI_REWRITE_ACCEPTED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    WARNING_ACCEPTED = "WARNING_ACCEPTED"
    BLOCKED = "BLOCKED"


class Phase8Decision(StrEnum):
    APPROVED_FOR_HUMAN_REVIEW = "APPROVED_FOR_HUMAN_REVIEW"
    APPROVED_WITH_WARNINGS_FOR_HUMAN_REVIEW = "APPROVED_WITH_WARNINGS_FOR_HUMAN_REVIEW"
    REWRITE_REQUIRED = "REWRITE_REQUIRED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"


class Phase8ReviewType(StrEnum):
    QUALITY_WARNING = "QUALITY_WARNING"
    UNSAFE_CLAIM_REVIEW = "UNSAFE_CLAIM_REVIEW"
    TONE_REVIEW = "TONE_REVIEW"
    COMPLIANCE_REVIEW = "COMPLIANCE_REVIEW"
    ECONOMIC_CLAIM_REVIEW = "ECONOMIC_CLAIM_REVIEW"
    EVIDENCE_MAPPING_REVIEW = "EVIDENCE_MAPPING_REVIEW"
    VARIANT_SELECTION_REVIEW = "VARIANT_SELECTION_REVIEW"
    AI_RULE_DISAGREEMENT = "AI_RULE_DISAGREEMENT"


class HumanReviewOperation(StrEnum):
    BUILD_HUMAN_REVIEW_QUEUE = "build_human_review_queue"
    MANUAL_REVIEW = "manual_review"
    MANUAL_EDIT = "manual_edit"
    FINAL_PRE_SEND_REVIEW = "final_pre_send_review"
    PHASE9_FULL_REVIEW = "phase9_full_review"


class HumanReviewRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_NO_ELIGIBLE_DRAFTS = "BLOCKED_BY_NO_ELIGIBLE_DRAFTS"
    BLOCKED_BY_DASHBOARD_CONFIG = "BLOCKED_BY_DASHBOARD_CONFIG"


class HumanReviewQueueStatus(StrEnum):
    QUEUED = "QUEUED"
    IN_REVIEW = "IN_REVIEW"
    EDIT_REQUIRED = "EDIT_REQUIRED"
    EDITED_NEEDS_CHECK = "EDITED_NEEDS_CHECK"
    REJUDGE_REQUIRED = "REJUDGE_REQUIRED"
    APPROVED_FOR_PHASE10 = "APPROVED_FOR_PHASE10"
    APPROVED_WITH_WARNINGS_FOR_PHASE10 = "APPROVED_WITH_WARNINGS_FOR_PHASE10"
    RETURNED_TO_PHASE7_REWRITE = "RETURNED_TO_PHASE7_REWRITE"
    RETURNED_TO_PHASE8_REJUDGE = "RETURNED_TO_PHASE8_REJUDGE"
    HELD = "HELD"
    REJECTED = "REJECTED"
    BLOCKED_BY_FINAL_PRE_SEND_CHECK = "BLOCKED_BY_FINAL_PRE_SEND_CHECK"


class HumanReviewDecisionValue(StrEnum):
    APPROVED_FOR_PHASE_10_SEND_QUEUE = "APPROVED_FOR_PHASE_10_SEND_QUEUE"
    APPROVED_WITH_MINOR_WARNINGS_FOR_PHASE_10 = "APPROVED_WITH_MINOR_WARNINGS_FOR_PHASE_10"
    NEEDS_MANUAL_EDIT = "NEEDS_MANUAL_EDIT"
    RETURN_TO_PHASE_7_REWRITE = "RETURN_TO_PHASE_7_REWRITE"
    RETURN_TO_PHASE_8_REJUDGE = "RETURN_TO_PHASE_8_REJUDGE"
    HOLD_FOR_LATER = "HOLD_FOR_LATER"
    REJECTED_BY_HUMAN = "REJECTED_BY_HUMAN"
    BLOCKED_BY_FINAL_PRE_SEND_CHECK = "BLOCKED_BY_FINAL_PRE_SEND_CHECK"


class ManualEditSeverity(StrEnum):
    NONE = "NONE"
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    MAJOR = "MAJOR"
    NEW_CLAIM_DETECTED = "NEW_CLAIM_DETECTED"
    ECONOMIC_WORDING_CHANGED = "ECONOMIC_WORDING_CHANGED"
    CTA_CHANGED = "CTA_CHANGED"


class FinalPreSendCheckStatus(StrEnum):
    PASSED = "PASSED"
    PASSED_WITH_WARNINGS = "PASSED_WITH_WARNINGS"
    FAILED = "FAILED"


class Phase9Decision(StrEnum):
    READY_FOR_PHASE_10_CONTROLLED_SEND_QUEUE = "READY_FOR_PHASE_10_CONTROLLED_SEND_QUEUE"
    READY_FOR_PHASE_10_WITH_WARNINGS = "READY_FOR_PHASE_10_WITH_WARNINGS"
    NEEDS_MANUAL_EDIT = "NEEDS_MANUAL_EDIT"
    RETURN_TO_PHASE_7_REWRITE = "RETURN_TO_PHASE_7_REWRITE"
    RETURN_TO_PHASE_8_REJUDGE = "RETURN_TO_PHASE_8_REJUDGE"
    HOLD_FOR_LATER = "HOLD_FOR_LATER"
    REJECTED_BY_HUMAN = "REJECTED_BY_HUMAN"
    BLOCKED_BY_FINAL_PRE_SEND_CHECK = "BLOCKED_BY_FINAL_PRE_SEND_CHECK"


class HumanReviewAuditAction(StrEnum):
    QUEUED = "QUEUED"
    ASSIGNED = "ASSIGNED"
    OPENED = "OPENED"
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    EDITED = "EDITED"
    APPROVED_FOR_PHASE10 = "APPROVED_FOR_PHASE10"
    REJECTED = "REJECTED"
    HELD = "HELD"
    RETURNED_TO_REWRITE = "RETURNED_TO_REWRITE"
    RETURNED_TO_JUDGE = "RETURNED_TO_JUDGE"
    FINAL_CHECK_FAILED = "FINAL_CHECK_FAILED"
    FINAL_CHECK_PASSED = "FINAL_CHECK_PASSED"
    EXPORT_CREATED = "EXPORT_CREATED"


class ReviewUserRole(StrEnum):
    OWNER = "owner"
    REVIEWER = "reviewer"
    READONLY = "readonly"


class ReviewLockStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    RELEASED = "RELEASED"


class SenderProviderType(StrEnum):
    CPANEL_SMTP = "cpanel_smtp"
    GOOGLE_WORKSPACE = "google_workspace"
    MAILGUN = "mailgun"
    AMAZON_SES = "amazon_ses"
    SENDGRID = "sendgrid"
    POSTMARK = "postmark"
    MANUAL_PLACEHOLDER = "manual_placeholder"


class SenderIdentityStatus(StrEnum):
    DRAFT = "DRAFT"
    CONFIGURED = "CONFIGURED"
    MANUAL_VERIFIED = "MANUAL_VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    DISABLED = "DISABLED"


class InboxMonitoringMode(StrEnum):
    PLANNED_ONLY = "planned_only"
    MANUAL_INBOX = "manual_inbox"
    FUTURE_IMAP = "future_imap"
    FUTURE_PROVIDER_WEBHOOK = "future_provider_webhook"


class BounceProcessingMode(StrEnum):
    PLANNED_ONLY = "planned_only"
    MANUAL_BOUNCE_REVIEW = "manual_bounce_review"
    FUTURE_IMAP_BOUNCE_PARSE = "future_imap_bounce_parse"
    FUTURE_PROVIDER_WEBHOOK = "future_provider_webhook"


class MailboxReadinessStatus(StrEnum):
    READY_FOR_MANUAL_REPLY_CHECK = "READY_FOR_MANUAL_REPLY_CHECK"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    FUTURE_PHASE_REQUIRED = "FUTURE_PHASE_REQUIRED"


class SendQueueOperation(StrEnum):
    BUILD_SEND_QUEUE = "build_send_queue"
    SEND_DRY_RUN = "send_dry_run"
    CONTROLLED_SEND = "controlled_send"
    PROVIDER_READINESS_CHECK = "provider_readiness_check"
    SUPPRESSION_IMPORT = "suppression_import"
    QUEUE_HOLD_CANCEL = "queue_hold_cancel"


class SendQueueRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_PROVIDER_CONFIG = "BLOCKED_BY_PROVIDER_CONFIG"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"
    BLOCKED_BY_LIMITS = "BLOCKED_BY_LIMITS"
    BLOCKED_BY_GLOBAL_KILL_SWITCH = "BLOCKED_BY_GLOBAL_KILL_SWITCH"
    BLOCKED_BY_PROVIDER_CIRCUIT_BREAKER = "BLOCKED_BY_PROVIDER_CIRCUIT_BREAKER"


class EmailSendQueueStatus(StrEnum):
    QUEUED_FOR_SEND = "QUEUED_FOR_SEND"
    SEND_DRY_RUN_PLANNED = "SEND_DRY_RUN_PLANNED"
    READY_TO_SEND_CONTROLLED = "READY_TO_SEND_CONTROLLED"
    BLOCKED_BY_SUPPRESSION = "BLOCKED_BY_SUPPRESSION"
    BLOCKED_BY_UNSUBSCRIBE = "BLOCKED_BY_UNSUBSCRIBE"
    BLOCKED_BY_DAILY_LIMIT = "BLOCKED_BY_DAILY_LIMIT"
    BLOCKED_BY_PROVIDER_CONFIG = "BLOCKED_BY_PROVIDER_CONFIG"
    BLOCKED_BY_FINAL_CHECK = "BLOCKED_BY_FINAL_CHECK"
    BLOCKED_DUPLICATE_SEND = "BLOCKED_DUPLICATE_SEND"
    BLOCKED_BY_GLOBAL_KILL_SWITCH = "BLOCKED_BY_GLOBAL_KILL_SWITCH"
    BLOCKED_BY_PROVIDER_CIRCUIT_BREAKER = "BLOCKED_BY_PROVIDER_CIRCUIT_BREAKER"
    BLOCKED_BY_SEND_WINDOW = "BLOCKED_BY_SEND_WINDOW"
    BLOCKED_BY_COUNTRY_COMPLIANCE = "BLOCKED_BY_COUNTRY_COMPLIANCE"
    HELD_BY_OPERATOR = "HELD_BY_OPERATOR"
    CANCELLED_BY_OPERATOR = "CANCELLED_BY_OPERATOR"
    SENDING = "SENDING"
    SENT_TO_PROVIDER = "SENT_TO_PROVIDER"
    FAILED_TRANSIENT = "FAILED_TRANSIENT"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    FAILED_PROVIDER_ERROR = "FAILED_PROVIDER_ERROR"
    FAILED_SMTP_ERROR = "FAILED_SMTP_ERROR"


class SendQueueLockStatus(StrEnum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    RELEASED = "RELEASED"


class SendAttemptStatus(StrEnum):
    DRY_RUN_PLANNED = "DRY_RUN_PLANNED"
    ATTEMPTED = "ATTEMPTED"
    SENT_TO_PROVIDER = "SENT_TO_PROVIDER"
    FAILED_PROVIDER_ERROR = "FAILED_PROVIDER_ERROR"
    FAILED_SMTP_ERROR = "FAILED_SMTP_ERROR"
    BLOCKED_BEFORE_SEND = "BLOCKED_BEFORE_SEND"


class ProviderStatus(StrEnum):
    ACCEPTED = "accepted"
    FAILED = "failed"
    DRY_RUN = "dry_run"
    BLOCKED = "blocked"


class EmailProviderType(StrEnum):
    NULL_DRY_RUN = "null_dry_run"
    CPANEL_SMTP = "cpanel_smtp"
    GOOGLE_WORKSPACE = "google_workspace"
    MAILGUN = "mailgun"
    AMAZON_SES = "amazon_ses"
    SENDGRID = "sendgrid"
    POSTMARK = "postmark"
    MANUAL_SMTP = "manual_smtp"


class SenderProviderConfigStatus(StrEnum):
    DRAFT = "DRAFT"
    CONFIGURED = "CONFIGURED"
    READY = "READY"
    DISABLED = "DISABLED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class SendWarmupStage(StrEnum):
    STARTER = "starter"
    CAUTIOUS = "cautious"
    NORMAL = "normal"


class ProviderCircuitStatus(StrEnum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"


class UnsubscribeTokenStatus(StrEnum):
    ACTIVE = "ACTIVE"
    USED = "USED"
    REVOKED = "REVOKED"


class UnsubscribeEventSource(StrEnum):
    PUBLIC_UNSUBSCRIBE_PAGE = "public_unsubscribe_page"
    MANUAL_UNSUBSCRIBE = "manual_unsubscribe"
    IMPORTED_SUPPRESSION = "imported_suppression"


class DeliveryEventType(StrEnum):
    ACCEPTED = "accepted"
    DELIVERED = "delivered"
    DEFERRED = "deferred"
    BOUNCED = "bounced"
    COMPLAINED = "complained"
    FAILED = "failed"
    UNKNOWN = "unknown"
    MANUAL_BOUNCE_REVIEW_NEEDED = "manual_bounce_review_needed"


class SendLimitCounterType(StrEnum):
    DAILY_TOTAL = "daily_total"
    PER_RUN = "per_run"
    PER_DOMAIN_DAILY = "per_domain_daily"
    RECIPIENT_COOLDOWN = "recipient_cooldown"
    RECIPIENT_DOMAIN_COOLDOWN = "recipient_domain_cooldown"
    CANDIDATE_BUSINESS_COOLDOWN = "candidate_business_cooldown"
    NORMALIZED_BUSINESS_NAME_COOLDOWN = "normalized_business_name_cooldown"
    CAMPAIGN_COOLDOWN = "campaign_cooldown"


class Phase10Decision(StrEnum):
    QUEUED_FOR_CONTROLLED_SEND = "QUEUED_FOR_CONTROLLED_SEND"
    SENT_TO_PROVIDER = "SENT_TO_PROVIDER"
    BLOCKED_BY_SUPPRESSION = "BLOCKED_BY_SUPPRESSION"
    BLOCKED_BY_PROVIDER_CONFIG = "BLOCKED_BY_PROVIDER_CONFIG"
    BLOCKED_BY_DAILY_LIMIT = "BLOCKED_BY_DAILY_LIMIT"
    BLOCKED_DUPLICATE_SEND = "BLOCKED_DUPLICATE_SEND"
    BLOCKED_BY_GLOBAL_KILL_SWITCH = "BLOCKED_BY_GLOBAL_KILL_SWITCH"
    BLOCKED_BY_PROVIDER_CIRCUIT_BREAKER = "BLOCKED_BY_PROVIDER_CIRCUIT_BREAKER"
    BLOCKED_BY_SEND_WINDOW = "BLOCKED_BY_SEND_WINDOW"
    BLOCKED_BY_COUNTRY_COMPLIANCE = "BLOCKED_BY_COUNTRY_COMPLIANCE"
    FAILED_SEND_ATTEMPT = "FAILED_SEND_ATTEMPT"
    HELD_FOR_MANUAL_SEND_REVIEW = "HELD_FOR_MANUAL_SEND_REVIEW"


class SendAuditAction(StrEnum):
    QUEUE_CREATED = "QUEUE_CREATED"
    QUEUE_BLOCKED = "QUEUE_BLOCKED"
    QUEUE_HELD = "QUEUE_HELD"
    QUEUE_CANCELLED = "QUEUE_CANCELLED"
    QUEUE_CLAIMED = "QUEUE_CLAIMED"
    QUEUE_CLAIM_RELEASED = "QUEUE_CLAIM_RELEASED"
    UNSUBSCRIBE_TOKEN_CREATED = "UNSUBSCRIBE_TOKEN_CREATED"
    MESSAGE_SNAPSHOT_CREATED = "MESSAGE_SNAPSHOT_CREATED"
    DRY_RUN_PLANNED = "DRY_RUN_PLANNED"
    SEND_ATTEMPT_STARTED = "SEND_ATTEMPT_STARTED"
    SEND_ATTEMPT_BLOCKED = "SEND_ATTEMPT_BLOCKED"
    SENT_TO_PROVIDER = "SENT_TO_PROVIDER"
    SEND_FAILED = "SEND_FAILED"
    SUPPRESSION_ADDED = "SUPPRESSION_ADDED"
    SUPPRESSION_IMPORTED = "SUPPRESSION_IMPORTED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    PROVIDER_CONFIG_CHECKED = "PROVIDER_CONFIG_CHECKED"
    PROVIDER_CIRCUIT_OPENED = "PROVIDER_CIRCUIT_OPENED"
    PROVIDER_CIRCUIT_RESET_REQUESTED = "PROVIDER_CIRCUIT_RESET_REQUESTED"


class SuppressionImportStatus(StrEnum):
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"


class InboxSyncOperation(StrEnum):
    IMAP_SYNC = "imap_sync"
    PROVIDER_EVENT_SYNC = "provider_event_sync"
    MANUAL_IMPORT = "manual_import"
    CLASSIFICATION = "classification"
    BOUNCE_PROCESSING = "bounce_processing"


class InboxSyncStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_CONFIG = "BLOCKED_BY_CONFIG"
    BLOCKED_BY_SAFETY = "BLOCKED_BY_SAFETY"


class InboundMessageType(StrEnum):
    REPLY = "reply"
    BOUNCE = "bounce"
    AUTO_REPLY = "auto_reply"
    OUT_OF_OFFICE = "out_of_office"
    PROVIDER_NOTIFICATION = "provider_notification"
    UNSUBSCRIBE_REQUEST = "unsubscribe_request"
    UNKNOWN = "unknown"


class InboundPartType(StrEnum):
    CLEAN_REPLY = "clean_reply"
    QUOTED_PREVIOUS_THREAD = "quoted_previous_thread"
    SIGNATURE = "signature"
    HTML_SANITIZED = "html_sanitized"
    PLAIN_TEXT_RAW = "plain_text_raw"
    ATTACHMENT_METADATA = "attachment_metadata"


class InboundMatchMethod(StrEnum):
    X_A2_HEADERS = "x_a2_headers"
    MESSAGE_ID_IN_REPLY_TO = "message_id_in_reply_to"
    REFERENCES_HEADER = "references_header"
    PROVIDER_MESSAGE_ID = "provider_message_id"
    RECIPIENT_SENDER_MATCH = "recipient_sender_match"
    SUBJECT_SIMILARITY = "subject_similarity"
    MANUAL_MATCH = "manual_match"
    UNKNOWN = "unknown"


class BounceSource(StrEnum):
    IMAP_DSN = "imap_dsn"
    PROVIDER_WEBHOOK = "provider_webhook"
    SMTP_ERROR = "smtp_error"
    MANUAL = "manual"
    UNKNOWN = "unknown"


class BounceType(StrEnum):
    HARD_BOUNCE = "hard_bounce"
    SOFT_BOUNCE = "soft_bounce"
    MAILBOX_FULL = "mailbox_full"
    DOMAIN_NOT_FOUND = "domain_not_found"
    RECIPIENT_INVALID = "recipient_invalid"
    TEMPORARY_DEFERRAL = "temporary_deferral"
    SPAM_REJECTION = "spam_rejection"
    POLICY_REJECTION = "policy_rejection"
    UNKNOWN_BOUNCE = "unknown_bounce"


class ReplyClassificationValue(StrEnum):
    POSITIVE_INTEREST = "POSITIVE_INTEREST"
    ASKING_PRICE = "ASKING_PRICE"
    ASKING_DETAILS = "ASKING_DETAILS"
    REQUESTED_CALL = "REQUESTED_CALL"
    NOT_INTERESTED = "NOT_INTERESTED"
    ALREADY_HAS_WEBSITE = "ALREADY_HAS_WEBSITE"
    WRONG_CONTACT = "WRONG_CONTACT"
    UNSUBSCRIBE_REQUEST = "UNSUBSCRIBE_REQUEST"
    AUTO_REPLY = "AUTO_REPLY"
    OUT_OF_OFFICE = "OUT_OF_OFFICE"
    BOUNCE_LIKE = "BOUNCE_LIKE"
    UNKNOWN_NEEDS_REVIEW = "UNKNOWN_NEEDS_REVIEW"


class ReplyClassifierType(StrEnum):
    RULE_BASED = "rule_based"
    AI_OPTIONAL = "ai_optional"
    MANUAL = "manual"


class LeadResponseLatestStatus(StrEnum):
    NO_RESPONSE_YET = "NO_RESPONSE_YET"
    REPLIED_POSITIVE = "REPLIED_POSITIVE"
    REPLIED_NEUTRAL = "REPLIED_NEUTRAL"
    REPLIED_NEGATIVE = "REPLIED_NEGATIVE"
    ASKED_FOR_PRICE = "ASKED_FOR_PRICE"
    ASKED_FOR_DETAILS = "ASKED_FOR_DETAILS"
    CALL_REQUESTED = "CALL_REQUESTED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    BOUNCED_HARD = "BOUNCED_HARD"
    BOUNCED_SOFT = "BOUNCED_SOFT"
    WRONG_CONTACT = "WRONG_CONTACT"
    AUTO_REPLY_ONLY = "AUTO_REPLY_ONLY"
    NEEDS_HUMAN_ACTION = "NEEDS_HUMAN_ACTION"
    CLOSED_NOT_INTERESTED = "CLOSED_NOT_INTERESTED"


class HumanResponseTaskType(StrEnum):
    REPLY_MANUALLY = "REPLY_MANUALLY"
    REVIEW_POSITIVE_REPLY = "REVIEW_POSITIVE_REPLY"
    SEND_PRICE_INFO = "SEND_PRICE_INFO"
    PREPARE_PROPOSAL = "PREPARE_PROPOSAL"
    VERIFY_CONTACT = "VERIFY_CONTACT"
    MARK_SUPPRESSED = "MARK_SUPPRESSED"
    CALL_REQUESTED_MANUAL = "CALL_REQUESTED_MANUAL"
    REVIEW_BOUNCE = "REVIEW_BOUNCE"
    REVIEW_UNKNOWN_REPLY = "REVIEW_UNKNOWN_REPLY"


class HumanTaskPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class HumanTaskStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class Phase11MailboxStatus(StrEnum):
    DRAFT = "DRAFT"
    CONFIGURED = "CONFIGURED"
    READY = "READY"
    DISABLED = "DISABLED"
    ERROR = "ERROR"


class LeadResponseTimelineEventType(StrEnum):
    EMAIL_SENT = "EMAIL_SENT"
    REPLY_RECEIVED = "REPLY_RECEIVED"
    BOUNCE_RECEIVED = "BOUNCE_RECEIVED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    STATUS_CHANGED = "STATUS_CHANGED"
    TASK_CREATED = "TASK_CREATED"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    SUPPRESSION_APPLIED = "SUPPRESSION_APPLIED"
    AUTO_REPLY_RECEIVED = "AUTO_REPLY_RECEIVED"


class InboundAuditAction(StrEnum):
    MESSAGE_IMPORTED = "MESSAGE_IMPORTED"
    MESSAGE_SKIPPED_DUPLICATE = "MESSAGE_SKIPPED_DUPLICATE"
    MESSAGE_MATCHED = "MESSAGE_MATCHED"
    BOUNCE_DETECTED = "BOUNCE_DETECTED"
    SUPPRESSION_APPLIED = "SUPPRESSION_APPLIED"
    REPLY_CLASSIFIED = "REPLY_CLASSIFIED"
    STATUS_UPDATED = "STATUS_UPDATED"
    TASK_CREATED = "TASK_CREATED"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_REJECTED = "WEBHOOK_REJECTED"
    SYNC_CHECKPOINT_UPDATED = "SYNC_CHECKPOINT_UPDATED"


class OpportunityType(StrEnum):
    WEBSITE_PROJECT = "WEBSITE_PROJECT"
    BOOKING_SYSTEM = "BOOKING_SYSTEM"
    QUOTE_REQUEST_SITE = "QUOTE_REQUEST_SITE"
    MENU_QR_SITE = "MENU_QR_SITE"
    WEBSITE_REFRESH = "WEBSITE_REFRESH"
    UNKNOWN = "UNKNOWN"


class OpportunityStatus(StrEnum):
    NEW_REPLY = "NEW_REPLY"
    QUALIFIED_INTEREST = "QUALIFIED_INTEREST"
    ASKED_PRICE = "ASKED_PRICE"
    ASKED_DETAILS = "ASKED_DETAILS"
    CALL_REQUESTED = "CALL_REQUESTED"
    NEEDS_MANUAL_RESPONSE = "NEEDS_MANUAL_RESPONSE"
    PROPOSAL_NEEDED = "PROPOSAL_NEEDED"
    AWAITING_HUMAN_ACTION = "AWAITING_HUMAN_ACTION"
    CLOSED_NOT_INTERESTED = "CLOSED_NOT_INTERESTED"
    CLOSED_WRONG_CONTACT = "CLOSED_WRONG_CONTACT"
    CLOSED_UNSUBSCRIBED = "CLOSED_UNSUBSCRIBED"
    CLOSED_BOUNCED = "CLOSED_BOUNCED"


class Phase12TaskType(StrEnum):
    PREPARE_REPLY = "PREPARE_REPLY"
    PREPARE_PRICE_RESPONSE = "PREPARE_PRICE_RESPONSE"
    PREPARE_PACKAGE_OUTLINE = "PREPARE_PACKAGE_OUTLINE"
    PREPARE_PROPOSAL = "PREPARE_PROPOSAL"
    SCHEDULE_MANUAL_CALL = "SCHEDULE_MANUAL_CALL"
    VERIFY_SCOPE = "VERIFY_SCOPE"
    CLOSE_LEAD = "CLOSE_LEAD"
    SUPPRESS_CONTACT = "SUPPRESS_CONTACT"


class PricingStrategy(StrEnum):
    ASK_SCOPE_FIRST = "ASK_SCOPE_FIRST"
    MANUAL_QUOTE_REQUIRED = "MANUAL_QUOTE_REQUIRED"
    SOFT_STARTER_POSITIONING = "SOFT_STARTER_POSITIONING"
    INTERNAL_RANGE_ONLY = "INTERNAL_RANGE_ONLY"
    DO_NOT_MENTION_PRICE = "DO_NOT_MENTION_PRICE"


class ResponseGuidanceType(StrEnum):
    PRICE_RESPONSE_GUIDANCE = "PRICE_RESPONSE_GUIDANCE"
    DETAILS_RESPONSE_GUIDANCE = "DETAILS_RESPONSE_GUIDANCE"
    CALL_RESPONSE_GUIDANCE = "CALL_RESPONSE_GUIDANCE"
    POSITIVE_INTEREST_RESPONSE_GUIDANCE = "POSITIVE_INTEREST_RESPONSE_GUIDANCE"
    NEGATIVE_REPLY_CLOSURE_GUIDANCE = "NEGATIVE_REPLY_CLOSURE_GUIDANCE"
    WRONG_CONTACT_GUIDANCE = "WRONG_CONTACT_GUIDANCE"


class ReplyDraftSuggestionStatus(StrEnum):
    DRAFT_SUGGESTED = "DRAFT_SUGGESTED"
    NEEDS_HUMAN_EDIT = "NEEDS_HUMAN_EDIT"
    BLOCKED_BY_POLICY = "BLOCKED_BY_POLICY"


class ReplyDraftGenerationMode(StrEnum):
    RULE_TEMPLATE = "rule_template"
    AI_OPTIONAL = "ai_optional"
    MANUAL = "manual"


class FollowupType(StrEnum):
    MANUAL_ONLY = "manual_only"
    NOT_ALLOWED = "not_allowed"
    FUTURE_PHASE = "future_phase"


class HumanSalesGateName(StrEnum):
    NO_AUTO_PRICE_GATE = "no_auto_price_gate"
    NO_AUTO_MEETING_GATE = "no_auto_meeting_gate"
    NO_AUTO_REPLY_GATE = "no_auto_reply_gate"
    MANUAL_QUOTE_REQUIRED_GATE = "manual_quote_required_gate"
    MANUAL_SEND_REQUIRED_GATE = "manual_send_required_gate"
    HUMAN_DECISION_REQUIRED_GATE = "human_decision_required_gate"
    NO_AUTO_PROPOSAL_GATE = "no_auto_proposal_gate"
    NO_AUTO_PAYMENT_LINK_GATE = "no_auto_payment_link_gate"


class Phase12DecisionValue(StrEnum):
    OPPORTUNITY_CREATED = "OPPORTUNITY_CREATED"
    MANUAL_RESPONSE_PLAN_READY = "MANUAL_RESPONSE_PLAN_READY"
    PRICE_RESPONSE_GUIDANCE_READY = "PRICE_RESPONSE_GUIDANCE_READY"
    CALL_REQUEST_TASK_CREATED = "CALL_REQUEST_TASK_CREATED"
    FOLLOWUP_ELIGIBLE_MANUAL_ONLY = "FOLLOWUP_ELIGIBLE_MANUAL_ONLY"
    CLOSED_NOT_INTERESTED = "CLOSED_NOT_INTERESTED"
    CLOSED_WRONG_CONTACT = "CLOSED_WRONG_CONTACT"
    CLOSED_SUPPRESSED = "CLOSED_SUPPRESSED"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class OpportunityAuditAction(StrEnum):
    OPPORTUNITY_CREATED = "OPPORTUNITY_CREATED"
    RESPONSE_PLAN_CREATED = "RESPONSE_PLAN_CREATED"
    PRICING_GUIDANCE_CREATED = "PRICING_GUIDANCE_CREATED"
    MEETING_GUIDANCE_CREATED = "MEETING_GUIDANCE_CREATED"
    TASK_CREATED = "TASK_CREATED"
    FOLLOWUP_ELIGIBILITY_SET = "FOLLOWUP_ELIGIBILITY_SET"
    STATUS_CHANGED = "STATUS_CHANGED"
    HUMAN_CONTROL_GATE_BLOCKED = "HUMAN_CONTROL_GATE_BLOCKED"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"


class SalesWorkspaceRunOperation(StrEnum):
    BUILD_SALES_WORKSPACE = "build_sales_workspace"
    GENERATE_SCOPE_CHECKLISTS = "generate_scope_checklists"
    GENERATE_PROPOSAL_CHECKLISTS = "generate_proposal_checklists"
    BUILD_MANUAL_FOLLOWUP_TASKS = "build_manual_followup_tasks"
    PHASE13_FULL_WORKSPACE_BUILD = "phase13_full_workspace_build"


class SalesWorkspaceRunStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED_BY_HUMAN_ONLY_GUARD_FAILURE = "BLOCKED_BY_HUMAN_ONLY_GUARD_FAILURE"


class SalesWorkspaceStatus(StrEnum):
    OPEN_NEW = "OPEN_NEW"
    NEEDS_MANUAL_REPLY = "NEEDS_MANUAL_REPLY"
    WAITING_FOR_SCOPE = "WAITING_FOR_SCOPE"
    SCOPE_RECEIVED = "SCOPE_RECEIVED"
    QUOTE_PREPARATION = "QUOTE_PREPARATION"
    QUOTE_READY_FOR_HUMAN_REVIEW = "QUOTE_READY_FOR_HUMAN_REVIEW"
    QUOTE_SENT_MANUALLY = "QUOTE_SENT_MANUALLY"
    PROPOSAL_CHECKLIST_READY = "PROPOSAL_CHECKLIST_READY"
    PROPOSAL_SENT_MANUALLY = "PROPOSAL_SENT_MANUALLY"
    MANUAL_CALL_NEEDED = "MANUAL_CALL_NEEDED"
    MANUAL_CALL_DONE = "MANUAL_CALL_DONE"
    WAITING_FOR_CUSTOMER = "WAITING_FOR_CUSTOMER"
    FOLLOWUP_MANUAL_ELIGIBLE = "FOLLOWUP_MANUAL_ELIGIBLE"
    CLOSED_WON = "CLOSED_WON"
    CLOSED_LOST = "CLOSED_LOST"
    CLOSED_NOT_INTERESTED = "CLOSED_NOT_INTERESTED"
    CLOSED_NO_RESPONSE = "CLOSED_NO_RESPONSE"
    CLOSED_WRONG_CONTACT = "CLOSED_WRONG_CONTACT"


class ScopeChecklistType(StrEnum):
    BEAUTY_SALON_BOOKING_SCOPE = "beauty_salon_booking_scope"
    BARBER_DIRECT_BOOKING_SCOPE = "barber_direct_booking_scope"
    CLEANING_QUOTE_REQUEST_SCOPE = "cleaning_quote_request_scope"
    CAFE_MENU_QR_SCOPE = "cafe_menu_qr_scope"
    GENERIC_WEBSITE_SCOPE = "generic_website_scope"


class ChecklistStatus(StrEnum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"
    COMPLETED = "COMPLETED"
    NOT_NEEDED = "NOT_NEEDED"


class ChecklistItemStatus(StrEnum):
    UNANSWERED = "UNANSWERED"
    ANSWERED = "ANSWERED"
    SKIPPED = "SKIPPED"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"


class ProposalType(StrEnum):
    STARTER_WEBSITE = "starter_website"
    BOOKING_SYSTEM_SITE = "booking_system_site"
    QUOTE_REQUEST_SITE = "quote_request_site"
    MENU_QR_SITE = "menu_qr_site"
    WEBSITE_REFRESH = "website_refresh"


class ProposalChecklistStatus(StrEnum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"
    READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
    APPROVED_MANUALLY = "APPROVED_MANUALLY"
    NOT_READY = "NOT_READY"


class ProposalChecklistItemStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class PricingWorksheetStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    NEEDS_SCOPE = "NEEDS_SCOPE"
    IN_PROGRESS = "IN_PROGRESS"
    READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
    APPROVED_MANUALLY = "APPROVED_MANUALLY"
    SENT_MANUALLY_OUTSIDE_SYSTEM = "SENT_MANUALLY_OUTSIDE_SYSTEM"


class Phase13GateName(StrEnum):
    SCOPE_MINIMUM_GATE = "scope_minimum_gate"
    MODULE_SELECTION_GATE = "module_selection_gate"
    CONTENT_READINESS_GATE = "content_readiness_gate"
    TECHNICAL_REQUIREMENT_GATE = "technical_requirement_gate"
    MANUAL_PRICE_INPUT_GATE = "manual_price_input_gate"
    HUMAN_QUOTE_APPROVAL_GATE = "human_quote_approval_gate"
    CLIENT_NEED_SUMMARY_GATE = "client_need_summary_gate"
    RECOMMENDED_PACKAGE_GATE = "recommended_package_gate"
    INCLUDED_MODULES_GATE = "included_modules_gate"
    EXCLUDED_ITEMS_GATE = "excluded_items_gate"
    CLIENT_RESPONSIBILITIES_GATE = "client_responsibilities_gate"
    MANUAL_TIMELINE_GATE = "manual_timeline_gate"
    MANUAL_PRICE_GATE = "manual_price_gate"
    RISK_NOTES_GATE = "risk_notes_gate"
    HUMAN_PROPOSAL_APPROVAL_GATE = "human_proposal_approval_gate"


class ManualFollowupStatus(StrEnum):
    PLANNED = "PLANNED"
    WAITING = "WAITING"
    DONE_MANUALLY = "DONE_MANUALLY"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"


class SalesTaskType(StrEnum):
    MANUAL_REPLY = "MANUAL_REPLY"
    ASK_SCOPE_QUESTIONS = "ASK_SCOPE_QUESTIONS"
    PREPARE_MANUAL_QUOTE = "PREPARE_MANUAL_QUOTE"
    REVIEW_MANUAL_QUOTE = "REVIEW_MANUAL_QUOTE"
    PREPARE_PROPOSAL_CHECKLIST = "PREPARE_PROPOSAL_CHECKLIST"
    SEND_PROPOSAL_MANUALLY = "SEND_PROPOSAL_MANUALLY"
    MANUAL_FOLLOWUP = "MANUAL_FOLLOWUP"
    MANUAL_CALL = "MANUAL_CALL"
    CLOSE_OPPORTUNITY = "CLOSE_OPPORTUNITY"


class SalesTaskStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"


class ManualCommunicationType(StrEnum):
    MANUAL_REPLY_SENT = "MANUAL_REPLY_SENT"
    MANUAL_FOLLOWUP_SENT = "MANUAL_FOLLOWUP_SENT"
    MANUAL_CALL_DONE = "MANUAL_CALL_DONE"
    MANUAL_QUOTE_SENT = "MANUAL_QUOTE_SENT"
    MANUAL_PROPOSAL_SENT = "MANUAL_PROPOSAL_SENT"
    CUSTOMER_REPLIED = "CUSTOMER_REPLIED"
    SCOPE_RECEIVED = "SCOPE_RECEIVED"
    PRICE_DISCUSSIONS_NOTED = "PRICE_DISCUSSIONS_NOTED"


class ManualCommunicationChannel(StrEnum):
    EMAIL = "email"
    PHONE = "phone"
    EXTERNAL_CALENDAR = "external_calendar"
    MANUAL_NOTE = "manual_note"
    OTHER = "other"


class OpportunityHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    NEEDS_SCOPE = "NEEDS_SCOPE"
    WAITING_CUSTOMER = "WAITING_CUSTOMER"
    AT_RISK_STALE = "AT_RISK_STALE"
    BLOCKED = "BLOCKED"
    CLOSED = "CLOSED"


class NextHumanActionType(StrEnum):
    ASK_SCOPE_QUESTIONS = "ASK_SCOPE_QUESTIONS"
    PREPARE_MANUAL_REPLY = "PREPARE_MANUAL_REPLY"
    PREPARE_MANUAL_QUOTE = "PREPARE_MANUAL_QUOTE"
    REVIEW_PROPOSAL_CHECKLIST = "REVIEW_PROPOSAL_CHECKLIST"
    MANUAL_CALL = "MANUAL_CALL"
    WAIT_FOR_CUSTOMER = "WAIT_FOR_CUSTOMER"
    MANUAL_FOLLOWUP = "MANUAL_FOLLOWUP"
    CLOSE_OPPORTUNITY = "CLOSE_OPPORTUNITY"


class NextHumanActionStatus(StrEnum):
    OPEN = "OPEN"
    DONE = "DONE"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"


class OpportunityCloseReason(StrEnum):
    NOT_INTERESTED = "NOT_INTERESTED"
    TOO_EXPENSIVE = "TOO_EXPENSIVE"
    ALREADY_HAS_PROVIDER = "ALREADY_HAS_PROVIDER"
    NO_RESPONSE = "NO_RESPONSE"
    WRONG_CONTACT = "WRONG_CONTACT"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    NOT_READY_NOW = "NOT_READY_NOW"
    SPAM_CONCERN = "SPAM_CONCERN"
    MANUAL_DECISION = "MANUAL_DECISION"
    WON = "WON"
    LOST_OTHER = "LOST_OTHER"


class HumanApprovalType(StrEnum):
    MANUAL_QUOTE_APPROVAL = "MANUAL_QUOTE_APPROVAL"
    PROPOSAL_CHECKLIST_APPROVAL = "PROPOSAL_CHECKLIST_APPROVAL"
    MANUAL_FOLLOWUP_DECISION = "MANUAL_FOLLOWUP_DECISION"
    OPPORTUNITY_CLOSE_DECISION = "OPPORTUNITY_CLOSE_DECISION"


class Phase13DecisionValue(StrEnum):
    SALES_WORKSPACE_READY = "SALES_WORKSPACE_READY"
    SCOPE_CHECKLIST_READY = "SCOPE_CHECKLIST_READY"
    PROPOSAL_CHECKLIST_READY = "PROPOSAL_CHECKLIST_READY"
    MANUAL_QUOTE_WORKSHEET_READY = "MANUAL_QUOTE_WORKSHEET_READY"
    MANUAL_FOLLOWUP_PLAN_READY = "MANUAL_FOLLOWUP_PLAN_READY"
    WAITING_FOR_HUMAN_ACTION = "WAITING_FOR_HUMAN_ACTION"
    CLOSED_MANUALLY = "CLOSED_MANUALLY"
    BLOCKED_BY_HUMAN_ONLY_GUARD = "BLOCKED_BY_HUMAN_ONLY_GUARD"


class Phase13AuditAction(StrEnum):
    WORKSPACE_CREATED = "WORKSPACE_CREATED"
    SCOPE_CHECKLIST_CREATED = "SCOPE_CHECKLIST_CREATED"
    SCOPE_ITEM_UPDATED = "SCOPE_ITEM_UPDATED"
    PROPOSAL_CHECKLIST_CREATED = "PROPOSAL_CHECKLIST_CREATED"
    PROPOSAL_ITEM_UPDATED = "PROPOSAL_ITEM_UPDATED"
    PRICING_WORKSHEET_CREATED = "PRICING_WORKSHEET_CREATED"
    PRICING_WORKSHEET_UPDATED = "PRICING_WORKSHEET_UPDATED"
    QUOTE_APPROVED_MANUALLY = "QUOTE_APPROVED_MANUALLY"
    FOLLOWUP_PLAN_CREATED = "FOLLOWUP_PLAN_CREATED"
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    MANUAL_COMMUNICATION_LOGGED = "MANUAL_COMMUNICATION_LOGGED"
    OPPORTUNITY_CLOSED = "OPPORTUNITY_CLOSED"
    HUMAN_ONLY_GUARD_BLOCKED = "HUMAN_ONLY_GUARD_BLOCKED"
    NEXT_ACTION_CREATED = "NEXT_ACTION_CREATED"
